
import type { Answer } from '@/server/autoGeneratedHooks/questioner/models/answer';
import type { CompletedQuestionerDto } from '@/server/autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Option } from '@/server/autoGeneratedHooks/questioner/models/option';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import type { QuestionerTemplateDto } from '@/server/autoGeneratedHooks/questioner/models/questionerTemplateDto';
import { QuestionType } from '@/server/autoGeneratedHooks/questioner/models/questionType';
import { isNotEmptyString, isValueDefined } from '@/utils/is';

const PERCENT_MULTIPLIER = 100;

/** Distribution of a single option within a choice question. */
export interface OptionDistribution {
  value: string;
  label: string;
  count: number;
  /** Percentage of total responses (0-100), guarded against divide-by-zero. */
  pct: number;
}

/** Aggregated result for one choice-type question. */
interface ChoiceQuestionStats {
  questionId: string;
  questionName: string;
  options: OptionDistribution[];
}

/** Aggregated result for one text-type question. */
interface TextQuestionStats {
  questionId: string;
  questionName: string;
  answers: string[];
}

/** A single day bucket of response counts. */
export interface ResponsesByDayEntry {
  day: string;
  count: number;
}

/** Full analytics result for the active template's responses. */
export interface AnalyticsStats {
  totalResponses: number;
  responsesByDay: ResponsesByDayEntry[];
  choiceQuestions: ChoiceQuestionStats[];
  textQuestions: TextQuestionStats[];
}

const CHOICE_TYPES: ReadonlySet<number> = new Set<number>([
  QuestionType.MultipleChoice,
  QuestionType.Checkbox,
  QuestionType.Radio,
  QuestionType.Dropdown,
]);

const MULTI_VALUE_TYPES: ReadonlySet<number> = new Set<number>([
  QuestionType.MultipleChoice,
  QuestionType.Checkbox,
]);

const EMPTY_STATS: AnalyticsStats = {
  totalResponses: 0,
  responsesByDay: [],
  choiceQuestions: [],
  textQuestions: [],
};

function getQuestions(record: { contents?: { questions?: Question[] } }): Question[] {
  const questions = record.contents?.questions;
  return Array.isArray(questions) ? questions : [];
}

function getQuestionId(question: Question): string {
  if (isNotEmptyString(question.id)) return question.id;
  if (isNotEmptyString(question.name)) return question.name;
  return '';
}

function getQuestionName(question: Question): string {
  if (isNotEmptyString(question.name)) return question.name;
  if (isNotEmptyString(question.id)) return question.id;
  return '';
}

function getDayBucket(record: CompletedQuestionerDto): string | undefined {
  const raw = isNotEmptyString(record.createdDate) ? record.createdDate : record.lastUpdatedDate;
  if (!isNotEmptyString(raw)) return undefined;
  const parsed = new Date(raw);
  if (Number.isNaN(parsed.getTime())) return undefined;
  return parsed.toISOString().slice(0, 'YYYY-MM-DD'.length);
}

/** Collect the option values a single response selected for a question. */
function getSelectedValues(answer: Answer | null | undefined, isMultiValue: boolean): string[] {
  if (!isValueDefined(answer)) return [];

  if (isMultiValue) {
    const multi = answer.multiValues;
    return Array.isArray(multi) ? multi.filter(isNotEmptyString) : [];
  }

  return isNotEmptyString(answer.stringValue) ? [answer.stringValue] : [];
}

function buildOptionDistributions(
  options: Option[],
  counts: Map<string, number>,
  totalResponses: number,
): OptionDistribution[] {
  return options.map((opt) => {
    const value = opt.value ?? '';
    const label = isNotEmptyString(opt.label) ? opt.label : value;
    const count = counts.get(value) ?? 0;
    const pct = totalResponses > 0 ? (count / totalResponses) * PERCENT_MULTIPLIER : 0;
    return { value, label, count, pct };
  });
}

/** Tally selected values across all responses for one choice question. */
function tallyChoiceQuestion(
  question: Question,
  responses: CompletedQuestionerDto[],
  totalResponses: number,
): ChoiceQuestionStats {
  const questionId = getQuestionId(question);
  const isMultiValue = MULTI_VALUE_TYPES.has(question.type ?? QuestionType.Text);
  const counts = new Map<string, number>();

  for (const response of responses) {
    const answered = getQuestions(response).find((q) => getQuestionId(q) === questionId);
    for (const value of getSelectedValues(answered?.answer, isMultiValue))
      counts.set(value, (counts.get(value) ?? 0) + 1);
  }

  const options = Array.isArray(question.options) ? question.options : [];
  return {
    questionId,
    questionName: getQuestionName(question),
    options: buildOptionDistributions(options, counts, totalResponses),
  };
}

/** Collect non-empty free-text answers across all responses for one text question. */
function collectTextAnswers(question: Question, responses: CompletedQuestionerDto[]): TextQuestionStats {
  const questionId = getQuestionId(question);
  const answers: string[] = [];

  for (const response of responses) {
    const answered = getQuestions(response).find((q) => getQuestionId(q) === questionId);
    const value = answered?.answer?.stringValue;
    if (isNotEmptyString(value)) answers.push(value);
  }

  return { questionId, questionName: getQuestionName(question), answers };
}

function computeResponsesByDay(responses: CompletedQuestionerDto[]): ResponsesByDayEntry[] {
  const counts = new Map<string, number>();
  for (const response of responses) {
    const day = getDayBucket(response);
    if (isValueDefined(day)) counts.set(day, (counts.get(day) ?? 0) + 1);
  }
  return Array.from(counts.entries())
    .map(([day, count]) => ({ day, count }))
    .sort((a, b) => a.day.localeCompare(b.day));
}

interface SplitQuestionStats {
  choiceQuestions: ChoiceQuestionStats[];
  textQuestions: TextQuestionStats[];
}

/** Split the template's defined questions into choice vs text aggregations. */
function splitQuestionStats(
  questions: Question[],
  matching: CompletedQuestionerDto[],
  totalResponses: number,
): SplitQuestionStats {
  const choiceQuestions: ChoiceQuestionStats[] = [];
  const textQuestions: TextQuestionStats[] = [];

  for (const question of questions) {
    const type = question.type ?? QuestionType.Text;
    if (CHOICE_TYPES.has(type))
      choiceQuestions.push(tallyChoiceQuestion(question, matching, totalResponses));
    else if (type === QuestionType.Text)
      textQuestions.push(collectTextAnswers(question, matching));
  }

  return { choiceQuestions, textQuestions };
}

/**
 * Compute client-side analytics for the active template's responses only.
 *
 * - Choice questions (Radio/Dropdown/Checkbox/MultipleChoice): one distribution row per
 *   option DEFINED on the question (zero-count options included). Matching is by option
 *   `value`. Checkbox/MultipleChoice tally EACH value in `answer.multiValues`.
 * - Text questions: collect non-empty `answer.stringValue` strings.
 * - `pct` is guarded against divide-by-zero (0 when there are no responses).
 */
export function computeAnalytics(
  activeTemplate: QuestionerTemplateDto | null | undefined,
  responses: CompletedQuestionerDto[] | null | undefined,
): AnalyticsStats {
  if (!isValueDefined(activeTemplate) || !isNotEmptyString(activeTemplate.externalId))
    return EMPTY_STATS;

  const templateId = activeTemplate.externalId;
  const all = Array.isArray(responses) ? responses : [];
  const matching = all.filter((r) => r.questionerTemplateExternalId === templateId);
  const totalResponses = matching.length;

  const split = splitQuestionStats(getQuestions(activeTemplate), matching, totalResponses);

  return {
    totalResponses,
    responsesByDay: computeResponsesByDay(matching),
    choiceQuestions: split.choiceQuestions,
    textQuestions: split.textQuestions,
  };
}
