/** Per-question tally + collection helpers for the response analytics. */
import type { Answer } from '@/server/autoGeneratedHooks/questioner/models/answer';
import type { CompletedQuestionerDto } from '@/server/autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Option } from '@/server/autoGeneratedHooks/questioner/models/option';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import { QuestionType } from '@/server/autoGeneratedHooks/questioner/models/questionType';
import { isNotEmptyString, isValueDefined } from '@/utils/is';

import type {
  ChoiceQuestionStats,
  DateQuestionStats,
  NumericBucket,
  NumericQuestionStats,
  OptionDistribution,
  ResponsesByDayEntry,
  TextQuestionStats,
} from './analyticsTypes';

const PERCENT_MULTIPLIER = 100;
const DAY_KEY_LENGTH = 'YYYY-MM-DD'.length;

const MULTI_VALUE_TYPES: ReadonlySet<number> = new Set<number>([
  QuestionType.MultipleChoice,
  QuestionType.Checkbox,
]);

export function getQuestions(record: { contents?: { questions?: Question[] } }): Question[] {
  const questions = record.contents?.questions;
  return Array.isArray(questions) ? questions : [];
}

function getQuestionId(question: Question): string {
  if (isNotEmptyString(question.id)) return question.id;
  if (isNotEmptyString(question.name)) return question.name;
  return '';
}

function getQuestionName(question: Question): string {
  if (isNotEmptyString(question.name)) return question.name;
  if (isNotEmptyString(question.id)) return question.id;
  return '';
}

function getDayBucket(record: CompletedQuestionerDto): string | undefined {
  const raw = isNotEmptyString(record.createdDate) ? record.createdDate : record.lastUpdatedDate;
  if (!isNotEmptyString(raw)) return undefined;
  const parsed = new Date(raw);
  if (Number.isNaN(parsed.getTime())) return undefined;
  return parsed.toISOString().slice(0, DAY_KEY_LENGTH);
}

/** Collect the option values a single response selected for a question. */
function getSelectedValues(answer: Answer | null | undefined, isMultiValue: boolean): string[] {
  if (!isValueDefined(answer)) return [];
  if (isMultiValue) {
    const multi = answer.multiValues;
    return Array.isArray(multi) ? multi.filter(isNotEmptyString) : [];
  }
  return isNotEmptyString(answer.stringValue) ? [answer.stringValue] : [];
}

function buildOptionDistributions(
  options: Option[],
  counts: Map<string, number>,
  totalResponses: number,
): OptionDistribution[] {
  return options.map((opt) => {
    const value = opt.value ?? '';
    const label = isNotEmptyString(opt.label) ? opt.label : value;
    const count = counts.get(value) ?? 0;
    const pct = totalResponses > 0 ? (count / totalResponses) * PERCENT_MULTIPLIER : 0;
    return { value, label, count, pct };
  });
}

/** Tally selected values across all responses for one choice question. */
export function tallyChoiceQuestion(
  question: Question,
  responses: CompletedQuestionerDto[],
  totalResponses: number,
): ChoiceQuestionStats {
  const questionId = getQuestionId(question);
  const isMultiValue = MULTI_VALUE_TYPES.has(question.type ?? QuestionType.Text);
  const counts = new Map<string, number>();

  for (const response of responses) {
    const answered = getQuestions(response).find((q) => getQuestionId(q) === questionId);
    for (const value of getSelectedValues(answered?.answer, isMultiValue))
      counts.set(value, (counts.get(value) ?? 0) + 1);
  }

  const options = Array.isArray(question.options) ? question.options : [];
  return {
    questionId,
    questionName: getQuestionName(question),
    options: buildOptionDistributions(options, counts, totalResponses),
  };
}

/** Collect non-empty free-text answers across all responses for one text question. */
export function collectTextAnswers(question: Question, responses: CompletedQuestionerDto[]): TextQuestionStats {
  const questionId = getQuestionId(question);
  const answers: string[] = [];
  for (const response of responses) {
    const answered = getQuestions(response).find((q) => getQuestionId(q) === questionId);
    const value = answered?.answer?.stringValue;
    if (isNotEmptyString(value)) answers.push(value);
  }
  return { questionId, questionName: getQuestionName(question), answers };
}

function collectNumericValues(question: Question, responses: CompletedQuestionerDto[]): number[] {
  const questionId = getQuestionId(question);
  const values: number[] = [];
  for (const response of responses) {
    const answered = getQuestions(response).find((q) => getQuestionId(q) === questionId);
    const numeric = answered?.answer?.numericValue;
    if (typeof numeric === 'number' && !Number.isNaN(numeric)) values.push(numeric);
  }
  return values;
}

function buildNumericDistribution(values: number[]): NumericBucket[] {
  const counts = new Map<number, number>();
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1);
  return Array.from(counts.entries())
    .map(([value, count]) => ({ value, count }))
    .sort((a, b) => a.value - b.value);
}

/** Aggregate a numeric question into count, average and distribution. */
export function tallyNumericQuestion(question: Question, responses: CompletedQuestionerDto[]): NumericQuestionStats {
  const values = collectNumericValues(question, responses);
  const count = values.length;
  const sum = values.reduce((acc, value) => acc + value, 0);
  const average = count > 0 ? sum / count : 0;
  return {
    questionId: getQuestionId(question),
    questionName: getQuestionName(question),
    count,
    average,
    distribution: buildNumericDistribution(values),
  };
}

/** Collect non-empty date answers (stored as stringValue) for one date question. */
export function collectDateAnswers(question: Question, responses: CompletedQuestionerDto[]): DateQuestionStats {
  const questionId = getQuestionId(question);
  const values: string[] = [];
  for (const response of responses) {
    const answered = getQuestions(response).find((q) => getQuestionId(q) === questionId);
    const value = answered?.answer?.stringValue;
    if (isNotEmptyString(value)) values.push(value);
  }
  return { questionId, questionName: getQuestionName(question), values };
}

export function computeResponsesByDay(responses: CompletedQuestionerDto[]): ResponsesByDayEntry[] {
  const counts = new Map<string, number>();
  for (const response of responses) {
    const day = getDayBucket(response);
    if (isValueDefined(day)) counts.set(day, (counts.get(day) ?? 0) + 1);
  }
  return Array.from(counts.entries())
    .map(([day, count]) => ({ day, count }))
    .sort((a, b) => a.day.localeCompare(b.day));
}
