import { NUMERIC_API_TYPES } from '@/components/DynamicForm/questionTypes/registry';
import type { CompletedQuestionerDto } from '@/server/autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import type { QuestionerTemplateDto } from '@/server/autoGeneratedHooks/questioner/models/questionerTemplateDto';
import { QuestionType } from '@/server/autoGeneratedHooks/questioner/models/questionType';
import { isNotEmptyString, isValueDefined } from '@/utils/is';

import {
  collectDateAnswers,
  collectTextAnswers,
  computeResponsesByDay,
  getQuestions,
  tallyChoiceQuestion,
  tallyMatrixQuestion,
  tallyNumericQuestion,
} from './analyticsTally';

import type { AnalyticsStats, SplitQuestionStats } from './analyticsTypes';

const CHOICE_TYPES: ReadonlySet<number> = new Set<number>([
  QuestionType.MultipleChoice,
  QuestionType.Checkbox,
  QuestionType.Radio,
  QuestionType.Dropdown,
  // Ranking's options ARE its answer values, so the choice tally counts how often each
  // option was ranked — a sensible aggregation alongside the other choice types.
  QuestionType.Ranking,
]);

const DATE_API_TYPE = QuestionType.Date;
const MATRIX_API_TYPE = QuestionType.Matrix;

const EMPTY_STATS: AnalyticsStats = {
  totalResponses: 0,
  responsesByDay: [],
  choiceQuestions: [],
  textQuestions: [],
  numericQuestions: [],
  dateQuestions: [],
};

/** Split the template's defined questions into choice/text/numeric/date aggregations. */
function splitQuestionStats(
  questions: Question[],
  matching: CompletedQuestionerDto[],
  totalResponses: number,
): SplitQuestionStats {
  const split: SplitQuestionStats = { choiceQuestions: [], textQuestions: [], numericQuestions: [], dateQuestions: [] };

  for (const question of questions) {
    const type = question.type ?? QuestionType.Text;
    if (type === MATRIX_API_TYPE)
      split.choiceQuestions.push(tallyMatrixQuestion(question, matching, totalResponses));
    else if (CHOICE_TYPES.has(type))
      split.choiceQuestions.push(tallyChoiceQuestion(question, matching, totalResponses));
    else if (NUMERIC_API_TYPES.has(type))
      split.numericQuestions.push(tallyNumericQuestion(question, matching));
    else if (type === DATE_API_TYPE)
      split.dateQuestions.push(collectDateAnswers(question, matching));
    else if (type === QuestionType.Text)
      split.textQuestions.push(collectTextAnswers(question, matching));
  }

  return split;
}

/**
 * Compute client-side analytics for the active template's responses only.
 *
 * - Choice questions (Radio/Dropdown/Checkbox/MultipleChoice): one distribution row per
 *   option DEFINED on the question (zero-count options included). Matching is by option
 *   `value`. Checkbox/MultipleChoice tally EACH value in `answer.multiValues`.
 * - Numeric questions (Rating/Nps/Number/LinearScale): count, average + value distribution.
 * - Date questions: collect non-empty `answer.stringValue` values.
 * - Text questions: collect non-empty `answer.stringValue` strings.
 * - `pct` is guarded against divide-by-zero (0 when there are no responses).
 */
export function computeAnalytics(
  activeTemplate: QuestionerTemplateDto | null | undefined,
  responses: CompletedQuestionerDto[] | null | undefined,
): AnalyticsStats {
  if (!isValueDefined(activeTemplate) || !isNotEmptyString(activeTemplate.externalId))
    return EMPTY_STATS;

  const templateId = activeTemplate.externalId;
  const all = Array.isArray(responses) ? responses : [];
  const matching = all.filter((r) => r.questionerTemplateExternalId === templateId);
  const totalResponses = matching.length;

  const split = splitQuestionStats(getQuestions(activeTemplate), matching, totalResponses);

  return {
    totalResponses,
    responsesByDay: computeResponsesByDay(matching),
    choiceQuestions: split.choiceQuestions,
    textQuestions: split.textQuestions,
    numericQuestions: split.numericQuestions,
    dateQuestions: split.dateQuestions,
  };
}

export type {
  AnalyticsStats,
  DateQuestionStats,
  NumericQuestionStats,
  OptionDistribution,
  ResponsesByDayEntry,
} from './analyticsTypes';
