

import type { CompletedQuestionerDto } from '@/server/autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import type { QuestionerTemplateDto } from '@/server/autoGeneratedHooks/questioner/models/questionerTemplateDto';
import { QuestionType } from '@/server/autoGeneratedHooks/questioner/models/questionType';

import { computeAnalytics } from './analyticsAggregator';

const TEMPLATE_ID = 'tpl-1';

function radioQuestion(): Question {
  return {
    id: 'q-color',
    name: 'Favourite colour',
    type: QuestionType.Radio,
    options: [
      { label: 'Red', value: 'red' },
      { label: 'Green', value: 'green' },
      { label: 'Blue', value: 'blue' },
    ],
  };
}

function checkboxQuestion(): Question {
  return {
    id: 'q-fruits',
    name: 'Fruits you like',
    type: QuestionType.Checkbox,
    options: [
      { label: 'Apple', value: 'apple' },
      { label: 'Banana', value: 'banana' },
      { label: 'Cherry', value: 'cherry' },
    ],
  };
}

function textQuestion(): Question {
  return { id: 'q-feedback', name: 'Any feedback?', type: QuestionType.Text };
}

function template(questions: Question[]): QuestionerTemplateDto {
  return {
    externalId: TEMPLATE_ID,
    name: 'Survey',
    isActive: true,
    contents: { questions },
  };
}

function response(
  questions: Question[],
  overrides: Partial<CompletedQuestionerDto> = {},
): CompletedQuestionerDto {
  return {
    externalId: `resp-${Math.random().toString(36).slice(2)}`,
    questionerTemplateExternalId: TEMPLATE_ID,
    createdDate: '2026-01-01T10:00:00.000Z',
    contents: { questions },
    ...overrides,
  };
}

function answeredRadio(value: string): Question {
  return { id: 'q-color', type: QuestionType.Radio, answer: { stringValue: value } };
}

function answeredCheckbox(values: string[]): Question {
  return { id: 'q-fruits', type: QuestionType.Checkbox, answer: { multiValues: values } };
}

function answeredText(value: string): Question {
  return { id: 'q-feedback', type: QuestionType.Text, answer: { stringValue: value } };
}

describe('computeAnalytics', () => {
  it('returns empty/zero stats when there is no active template', () => {
    const stats = computeAnalytics(null, [response([answeredRadio('red')])]);
    expect(stats.totalResponses).toBe(0);
    expect(stats.responsesByDay).toEqual([]);
    expect(stats.choiceQuestions).toEqual([]);
    expect(stats.textQuestions).toEqual([]);
  });

  it('returns empty/zero stats when the template has no externalId', () => {
    const tpl: QuestionerTemplateDto = { name: 'x', contents: { questions: [radioQuestion()] } };
    const stats = computeAnalytics(tpl, [response([answeredRadio('red')])]);
    expect(stats.totalResponses).toBe(0);
    expect(stats.choiceQuestions).toEqual([]);
  });

  it('returns zero totals and zero-count options when there are no responses', () => {
    const stats = computeAnalytics(template([radioQuestion()]), []);
    expect(stats.totalResponses).toBe(0);
    expect(stats.choiceQuestions).toHaveLength(1);
    const opts = stats.choiceQuestions[0].options;
    expect(opts.map((o) => o.value)).toEqual(['red', 'green', 'blue']);
    expect(opts.every((o) => o.count === 0)).toBe(true);
    // divide-by-zero guard: pct must be 0, not NaN
    expect(opts.every((o) => o.pct === 0)).toBe(true);
  });

  it('handles null responses input as empty', () => {
    const stats = computeAnalytics(template([radioQuestion()]), null);
    expect(stats.totalResponses).toBe(0);
    expect(stats.choiceQuestions[0].options).toHaveLength(3);
  });

  it('includes EVERY defined option, even those never selected (zero-count)', () => {
    const responses = [
      response([answeredRadio('red')]),
      response([answeredRadio('red')]),
    ];
    const stats = computeAnalytics(template([radioQuestion()]), responses);
    const opts = stats.choiceQuestions[0].options;
    const byValue = Object.fromEntries(opts.map((o) => [o.value, o]));
    expect(byValue.red.count).toBe(2);
    expect(byValue.green.count).toBe(0);
    expect(byValue.blue.count).toBe(0);
    // green and blue still present as rows
    expect(opts).toHaveLength(3);
  });

  it('matches answers to options by value, not label', () => {
    // answer stringValue is the VALUE 'green', not the label 'Green'
    const stats = computeAnalytics(template([radioQuestion()]), [response([answeredRadio('green')])]);
    const green = stats.choiceQuestions[0].options.find((o) => o.value === 'green');
    expect(green?.count).toBe(1);
    expect(green?.label).toBe('Green');
  });

  it('computes pct as count/total * 100', () => {
    const responses = [
      response([answeredRadio('red')]),
      response([answeredRadio('red')]),
      response([answeredRadio('green')]),
      response([answeredRadio('blue')]),
    ];
    const stats = computeAnalytics(template([radioQuestion()]), responses);
    const byValue = Object.fromEntries(stats.choiceQuestions[0].options.map((o) => [o.value, o]));
    expect(stats.totalResponses).toBe(4);
    expect(byValue.red.pct).toBe(50);
    expect(byValue.green.pct).toBe(25);
    expect(byValue.blue.pct).toBe(25);
  });

  it('tallies EACH selected value for checkbox/multi-select questions', () => {
    const responses = [
      response([answeredCheckbox(['apple', 'banana'])]),
      response([answeredCheckbox(['apple', 'cherry'])]),
      response([answeredCheckbox(['apple'])]),
    ];
    const stats = computeAnalytics(template([checkboxQuestion()]), responses);
    const byValue = Object.fromEntries(stats.choiceQuestions[0].options.map((o) => [o.value, o]));
    expect(stats.totalResponses).toBe(3);
    expect(byValue.apple.count).toBe(3);
    expect(byValue.banana.count).toBe(1);
    expect(byValue.cherry.count).toBe(1);
    // pct is relative to total RESPONSES, so apple in all 3 => 100%
    expect(byValue.apple.pct).toBe(100);
  });

  it('ignores empty/whitespace values in multiValues', () => {
    const responses = [response([answeredCheckbox(['apple', ''])])];
    const stats = computeAnalytics(template([checkboxQuestion()]), responses);
    const byValue = Object.fromEntries(stats.choiceQuestions[0].options.map((o) => [o.value, o]));
    expect(byValue.apple.count).toBe(1);
  });

  it('collects non-empty free-text answers for Text questions', () => {
    const responses = [
      response([answeredText('Great survey')]),
      response([answeredText('')]),
      response([answeredText('Loved it')]),
      response([{ id: 'q-feedback', type: QuestionType.Text, answer: null }]),
    ];
    const stats = computeAnalytics(template([textQuestion()]), responses);
    expect(stats.textQuestions).toHaveLength(1);
    expect(stats.textQuestions[0].answers).toEqual(['Great survey', 'Loved it']);
    expect(stats.choiceQuestions).toHaveLength(0);
  });

  it('filters out responses belonging to a different template', () => {
    const responses = [
      response([answeredRadio('red')]),
      response([answeredRadio('green')], { questionerTemplateExternalId: 'other-tpl' }),
    ];
    const stats = computeAnalytics(template([radioQuestion()]), responses);
    expect(stats.totalResponses).toBe(1);
    const byValue = Object.fromEntries(stats.choiceQuestions[0].options.map((o) => [o.value, o]));
    expect(byValue.red.count).toBe(1);
    expect(byValue.green.count).toBe(0);
  });

  it('buckets responses by day from createdDate', () => {
    const responses = [
      response([answeredRadio('red')], { createdDate: '2026-01-01T08:00:00.000Z' }),
      response([answeredRadio('red')], { createdDate: '2026-01-01T20:00:00.000Z' }),
      response([answeredRadio('green')], { createdDate: '2026-01-03T09:00:00.000Z' }),
    ];
    const stats = computeAnalytics(template([radioQuestion()]), responses);
    expect(stats.responsesByDay).toEqual([
      { day: '2026-01-01', count: 2 },
      { day: '2026-01-03', count: 1 },
    ]);
  });

  it('falls back to lastUpdatedDate when createdDate is missing for day buckets', () => {
    const responses = [
      response([answeredRadio('red')], { createdDate: undefined, lastUpdatedDate: '2026-02-05T09:00:00.000Z' }),
    ];
    const stats = computeAnalytics(template([radioQuestion()]), responses);
    expect(stats.responsesByDay).toEqual([{ day: '2026-02-05', count: 1 }]);
  });

  it('skips responses with no parseable date in day buckets but still counts them in total', () => {
    const responses = [
      response([answeredRadio('red')], { createdDate: 'not-a-date', lastUpdatedDate: undefined }),
      response([answeredRadio('red')], { createdDate: '2026-01-01T08:00:00.000Z' }),
    ];
    const stats = computeAnalytics(template([radioQuestion()]), responses);
    expect(stats.totalResponses).toBe(2);
    expect(stats.responsesByDay).toEqual([{ day: '2026-01-01', count: 1 }]);
  });

  it('handles mixed choice + text questions in one template', () => {
    const tpl = template([radioQuestion(), textQuestion(), checkboxQuestion()]);
    const responses = [
      response([answeredRadio('red'), answeredText('Nice'), answeredCheckbox(['apple'])]),
    ];
    const stats = computeAnalytics(tpl, responses);
    expect(stats.choiceQuestions).toHaveLength(2);
    expect(stats.textQuestions).toHaveLength(1);
    expect(stats.textQuestions[0].answers).toEqual(['Nice']);
  });

  it('uses the option value as label when label is missing', () => {
    const q: Question = {
      id: 'q-x',
      name: 'X',
      type: QuestionType.Dropdown,
      options: [{ value: 'only-value' }],
    };
    const stats = computeAnalytics(template([q]), [
      response([{ id: 'q-x', type: QuestionType.Dropdown, answer: { stringValue: 'only-value' } }]),
    ]);
    expect(stats.choiceQuestions[0].options[0].label).toBe('only-value');
    expect(stats.choiceQuestions[0].options[0].count).toBe(1);
  });

  describe('numeric and date aggregation', () => {
    function ratingQuestion(): Question {
      return { id: 'q-rate', name: 'Rate us', type: QuestionType.Rating };
    }
    function answeredRating(value: number): Question {
      return { id: 'q-rate', type: QuestionType.Rating, answer: { numericValue: value } };
    }
    function dateQuestion(): Question {
      return { id: 'q-date', name: 'When?', type: QuestionType.Date };
    }
    function answeredDate(value: string): Question {
      return { id: 'q-date', type: QuestionType.Date, answer: { stringValue: value } };
    }

    it('aggregates numeric answers into count, average and ascending distribution', () => {
      const responses = [
        response([answeredRating(5)]),
        response([answeredRating(3)]),
        response([answeredRating(5)]),
        response([answeredRating(1)]),
      ];
      const stats = computeAnalytics(template([ratingQuestion()]), responses);
      expect(stats.numericQuestions).toHaveLength(1);
      const numeric = stats.numericQuestions[0];
      expect(numeric.count).toBe(4);
      expect(numeric.average).toBe(3.5);
      expect(numeric.distribution).toEqual([
        { value: 1, count: 1 },
        { value: 3, count: 1 },
        { value: 5, count: 2 },
      ]);
      // numeric questions are NOT treated as choice/text
      expect(stats.choiceQuestions).toHaveLength(0);
      expect(stats.textQuestions).toHaveLength(0);
    });

    it('reports zero average and empty distribution when no numeric answers', () => {
      const stats = computeAnalytics(template([ratingQuestion()]), []);
      expect(stats.numericQuestions[0].count).toBe(0);
      expect(stats.numericQuestions[0].average).toBe(0);
      expect(stats.numericQuestions[0].distribution).toEqual([]);
    });

    it('collects non-empty date answers as a list', () => {
      const responses = [
        response([answeredDate('2026-06-01')]),
        response([answeredDate('')]),
        response([answeredDate('2026-06-03')]),
      ];
      const stats = computeAnalytics(template([dateQuestion()]), responses);
      expect(stats.dateQuestions).toHaveLength(1);
      expect(stats.dateQuestions[0].values).toEqual(['2026-06-01', '2026-06-03']);
    });
  });
});
