import type { CompletedQuestionerDto } from '@/server/autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import { QuestionType } from '@/server/autoGeneratedHooks/questioner/models/questionType';

import { computeFunnel } from './analyticsFunnel';

const TEMPLATE_ID = 'tpl-1';

function q(id: string, name: string, page: number): Question {
  return { id, name, type: QuestionType.Text, page };
}

function response(questions: Question[]): CompletedQuestionerDto {
  return {
    externalId: `resp-${Math.random().toString(36).slice(2)}`,
    questionerTemplateExternalId: TEMPLATE_ID,
    createdDate: '2026-01-01T10:00:00.000Z',
    contents: { questions },
  };
}

function answered(id: string, value: string): Question {
  return { id, type: QuestionType.Text, answer: { stringValue: value } };
}

function nullAnswer(id: string): Question {
  return { id, type: QuestionType.Text, answer: null };
}

function stepFor(steps: Array<{ questionId: string }>, id: string): number {
  return steps.findIndex((s) => s.questionId === id);
}

describe('computeFunnel (completion / answered-rate funnel — NOT drop-off)', () => {
  it('returns an empty funnel when there are no questions', () => {
    const funnel = computeFunnel([], [response([answered('q1', 'x')])]);
    expect(funnel.totalResponses).toBe(0);
    expect(funnel.questionSteps).toEqual([]);
    expect(funnel.pageSteps).toEqual([]);
  });

  it('computes per-question answered rate (present vs null)', () => {
    const questions = [q('q1', 'First', 0), q('q2', 'Second', 0)];
    const responses = [
      response([answered('q1', 'a'), answered('q2', 'b')]),
      response([answered('q1', 'a'), nullAnswer('q2')]),
      response([answered('q1', 'a')]), // q2 entirely absent
      response([nullAnswer('q1'), answered('q2', 'b')]),
    ];
    const funnel = computeFunnel(questions, responses);
    expect(funnel.totalResponses).toBe(4);
    const q1 = funnel.questionSteps[stepFor(funnel.questionSteps, 'q1')];
    const q2 = funnel.questionSteps[stepFor(funnel.questionSteps, 'q2')];
    expect(q1.answered).toBe(3);
    expect(q1.answeredPct).toBe(75);
    expect(q2.answered).toBe(2);
    expect(q2.answeredPct).toBe(50);
  });

  it('treats empty-string answers as not answered', () => {
    const questions = [q('q1', 'First', 0)];
    const responses = [response([answered('q1', '')]), response([answered('q1', 'x')])];
    const funnel = computeFunnel(questions, responses);
    expect(funnel.questionSteps[0].answered).toBe(1);
  });

  it('guards answeredPct against divide-by-zero when there are no responses', () => {
    const funnel = computeFunnel([q('q1', 'First', 0)], []);
    expect(funnel.totalResponses).toBe(0);
    expect(funnel.questionSteps[0].answeredPct).toBe(0);
  });

  it('computes per-page reach (>= one answered question on the page), sorted by page', () => {
    const questions = [
      q('q1', 'First', 1),
      q('q2', 'Second', 1),
      q('q3', 'Third', 2),
    ];
    const responses = [
      // reaches page 1 (q1) and page 2 (q3)
      response([answered('q1', 'a'), nullAnswer('q2'), answered('q3', 'c')]),
      // reaches page 1 (q2) only
      response([nullAnswer('q1'), answered('q2', 'b'), nullAnswer('q3')]),
      // reaches page 1 only (no page-2 answer)
      response([answered('q1', 'a')]),
    ];
    const funnel = computeFunnel(questions, responses);
    expect(funnel.pageSteps.map((p) => p.page)).toEqual([1, 2]);
    const page1 = funnel.pageSteps[0];
    const page2 = funnel.pageSteps[1];
    expect(page1.reached).toBe(3); // all three answered something on page 1
    expect(page1.reachedPct).toBe(100);
    expect(page2.reached).toBe(1); // only the first response answered q3
    expect(Math.round(page2.reachedPct)).toBe(33);
  });

  it('defaults a missing page to page 0', () => {
    const questions: Question[] = [{ id: 'q1', name: 'First', type: QuestionType.Text }];
    const funnel = computeFunnel(questions, [response([answered('q1', 'x')])]);
    expect(funnel.questionSteps[0].page).toBe(0);
    expect(funnel.pageSteps[0].page).toBe(0);
  });
});
