/**
 * Analytics aggregation for the advanced question types (Ranking, Matrix).
 *
 * Both store their answer in `multiValues`. Ranking reuses the choice tally (its options
 * ARE its values); Matrix uses a dedicated tally that buckets `"rowId:colId"` cells with
 * readable "Row → Column" labels. These tests guard sensible aggregation without
 * regressing the existing choice/numeric/date/text paths.
 */
import type { CompletedQuestionerDto } from '@/server/autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import type { QuestionerTemplateDto } from '@/server/autoGeneratedHooks/questioner/models/questionerTemplateDto';
import { QuestionType } from '@/server/autoGeneratedHooks/questioner/models/questionType';

import { computeAnalytics } from './analyticsAggregator';

const TEMPLATE_ID = 'tpl-adv';

function template(questions: Question[]): QuestionerTemplateDto {
  return { externalId: TEMPLATE_ID, name: 'Survey', isActive: true, contents: { questions } };
}

function response(questions: Question[]): CompletedQuestionerDto {
  return {
    externalId: `resp-${Math.random().toString(36).slice(2)}`,
    questionerTemplateExternalId: TEMPLATE_ID,
    createdDate: '2026-01-01T10:00:00.000Z',
    contents: { questions },
  };
}

function rankingQuestion(): Question {
  return {
    id: 'q-rank',
    name: 'Rank these',
    type: QuestionType.Ranking,
    options: [
      { label: 'Alpha', value: 'a' },
      { label: 'Beta', value: 'b' },
      { label: 'Gamma', value: 'c' },
    ],
  };
}

function answeredRanking(ordered: string[]): Question {
  return { id: 'q-rank', type: QuestionType.Ranking, answer: { multiValues: ordered } };
}

function matrixQuestion(): Question {
  return {
    id: 'q-grid',
    name: 'Rate each',
    type: QuestionType.Matrix,
    options: [
      { label: 'Speed', value: 'row:r1' },
      { label: 'Price', value: 'row:r2' },
      { label: 'Low', value: 'col:c1' },
      { label: 'High', value: 'col:c2' },
    ],
  };
}

function answeredMatrix(pairs: string[]): Question {
  return { id: 'q-grid', type: QuestionType.Matrix, answer: { multiValues: pairs } };
}

describe('computeAnalytics - Ranking', () => {
  it('tallies ranking as a choice distribution over its options', () => {
    const responses = [response([answeredRanking(['a', 'b', 'c'])]), response([answeredRanking(['c', 'a', 'b'])])];
    const stats = computeAnalytics(template([rankingQuestion()]), responses);
    expect(stats.choiceQuestions).toHaveLength(1);
    const byValue = Object.fromEntries(stats.choiceQuestions[0].options.map((o) => [o.value, o.count]));
    // every option ranked once per response → 2 each
    expect(byValue).toEqual({ a: 2, b: 2, c: 2 });
  });

  it('does not route ranking into numeric/text/date buckets', () => {
    const stats = computeAnalytics(template([rankingQuestion()]), [response([answeredRanking(['a', 'b', 'c'])])]);
    expect(stats.numericQuestions).toHaveLength(0);
    expect(stats.textQuestions).toHaveLength(0);
    expect(stats.dateQuestions).toHaveLength(0);
  });
});

describe('computeAnalytics - Matrix', () => {
  it('tallies each (row → column) cell with readable labels', () => {
    const responses = [
      response([answeredMatrix(['r1:c1', 'r2:c2'])]),
      response([answeredMatrix(['r1:c1', 'r2:c1'])]),
    ];
    const stats = computeAnalytics(template([matrixQuestion()]), responses);
    expect(stats.choiceQuestions).toHaveLength(1);
    const byValue = Object.fromEntries(stats.choiceQuestions[0].options.map((o) => [o.value, o]));
    expect(byValue['r1:c1'].count).toBe(2);
    expect(byValue['r1:c1'].label).toBe('Speed → Low');
    expect(byValue['r2:c2'].count).toBe(1);
    expect(byValue['r2:c1'].count).toBe(1);
  });

  it('guards pct against divide-by-zero', () => {
    const stats = computeAnalytics(template([matrixQuestion()]), []);
    expect(stats.choiceQuestions).toHaveLength(1);
    expect(stats.choiceQuestions[0].options.every((o) => o.pct === 0)).toBe(true);
  });
});
