import type { CompletedQuestionerDto } from '@/server/autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import { QuestionType } from '@/server/autoGeneratedHooks/questioner/models/questionType';

import { computeCrosstab } from './analyticsCrosstab';

const TEMPLATE_ID = 'tpl-1';

function colorQuestion(): Question {
  return {
    id: 'q-color',
    name: 'Colour',
    type: QuestionType.Radio,
    options: [
      { label: 'Red', value: 'red' },
      { label: 'Blue', value: 'blue' },
    ],
  };
}

function genderQuestion(): Question {
  return {
    id: 'q-gender',
    name: 'Gender',
    type: QuestionType.Radio,
    options: [
      { label: 'F', value: 'f' },
      { label: 'M', value: 'm' },
    ],
  };
}

function fruitsQuestion(): Question {
  return { id: 'q-fruits', name: 'Fruits', type: QuestionType.Checkbox };
}

function ratingQuestion(): Question {
  return { id: 'q-rate', name: 'Rating', type: QuestionType.Rating };
}

function response(questions: Question[]): CompletedQuestionerDto {
  return {
    externalId: `resp-${Math.random().toString(36).slice(2)}`,
    questionerTemplateExternalId: TEMPLATE_ID,
    createdDate: '2026-01-01T10:00:00.000Z',
    contents: { questions },
  };
}

function ansRadio(id: string, value: string): Question {
  return { id, type: QuestionType.Radio, answer: { stringValue: value } };
}

function ansCheckbox(id: string, values: string[]): Question {
  return { id, type: QuestionType.Checkbox, answer: { multiValues: values } };
}

function ansRating(id: string, value: number): Question {
  return { id, type: QuestionType.Rating, answer: { numericValue: value } };
}

function cellAt(rows: ReturnType<typeof computeCrosstab>['rows'], bucket: string, colIndex: number): number {
  const row = rows.find((r) => r.bucket === bucket);
  return row?.cells[colIndex]?.count ?? 0;
}

describe('computeCrosstab', () => {
  const defs = [colorQuestion(), genderQuestion()];

  it('returns an empty result when the row question is missing', () => {
    const result = computeCrosstab(defs, [], 'missing', 'q-gender');
    expect(result.rows).toEqual([]);
    expect(result.matchedResponses).toBe(0);
  });

  it('returns an empty result when row and col are the same question', () => {
    const result = computeCrosstab(defs, [response([ansRadio('q-color', 'red')])], 'q-color', 'q-color');
    expect(result.rows).toEqual([]);
    expect(result.colBuckets).toEqual([]);
  });

  it('builds a count matrix joining responses that answered both questions', () => {
    const responses = [
      response([ansRadio('q-color', 'red'), ansRadio('q-gender', 'f')]),
      response([ansRadio('q-color', 'red'), ansRadio('q-gender', 'm')]),
      response([ansRadio('q-color', 'blue'), ansRadio('q-gender', 'f')]),
      response([ansRadio('q-color', 'red'), ansRadio('q-gender', 'f')]),
    ];
    const result = computeCrosstab(defs, responses, 'q-color', 'q-gender');
    expect(result.matchedResponses).toBe(4);
    expect(result.colBuckets).toEqual(['f', 'm']); // sorted
    // red x f = 2, red x m = 1, blue x f = 1
    expect(cellAt(result.rows, 'red', 0)).toBe(2);
    expect(cellAt(result.rows, 'red', 1)).toBe(1);
    expect(cellAt(result.rows, 'blue', 0)).toBe(1);
    expect(cellAt(result.rows, 'blue', 1)).toBe(0);
  });

  it('exposes correct row totals, column totals and metadata', () => {
    const responses = [
      response([ansRadio('q-color', 'red'), ansRadio('q-gender', 'f')]),
      response([ansRadio('q-color', 'red'), ansRadio('q-gender', 'm')]),
      response([ansRadio('q-color', 'blue'), ansRadio('q-gender', 'f')]),
    ];
    const result = computeCrosstab(defs, responses, 'q-color', 'q-gender');
    expect(result.rowQuestionName).toBe('Colour');
    expect(result.colQuestionName).toBe('Gender');
    const redRow = result.rows.find((r) => r.bucket === 'red');
    expect(redRow?.total).toBe(2);
    expect(result.colTotals).toEqual([2, 1]); // f total 2, m total 1
  });

  it('excludes responses that did not answer one of the two questions', () => {
    const responses = [
      response([ansRadio('q-color', 'red'), ansRadio('q-gender', 'f')]),
      response([ansRadio('q-color', 'red')]), // no gender
      response([ansRadio('q-gender', 'm')]), // no colour
    ];
    const result = computeCrosstab(defs, responses, 'q-color', 'q-gender');
    expect(result.matchedResponses).toBe(1);
    expect(cellAt(result.rows, 'red', 0)).toBe(1);
  });

  it('counts EACH selected value for multi-value answers on both axes', () => {
    const localDefs = [fruitsQuestion(), genderQuestion()];
    const responses = [
      response([ansCheckbox('q-fruits', ['apple', 'banana']), ansRadio('q-gender', 'f')]),
      response([ansCheckbox('q-fruits', ['apple']), ansRadio('q-gender', 'm')]),
    ];
    const result = computeCrosstab(localDefs, responses, 'q-fruits', 'q-gender');
    // apple appears with f once and m once; banana with f once
    expect(cellAt(result.rows, 'apple', 0)).toBe(1); // apple x f
    expect(cellAt(result.rows, 'apple', 1)).toBe(1); // apple x m
    expect(cellAt(result.rows, 'banana', 0)).toBe(1); // banana x f
    // matched responses is by RESPONSE, not by value pair
    expect(result.matchedResponses).toBe(2);
  });

  it('buckets numeric answers by their stringified value', () => {
    const localDefs = [ratingQuestion(), genderQuestion()];
    const responses = [
      response([ansRating('q-rate', 5), ansRadio('q-gender', 'f')]),
      response([ansRating('q-rate', 5), ansRadio('q-gender', 'm')]),
      response([ansRating('q-rate', 3), ansRadio('q-gender', 'f')]),
    ];
    const result = computeCrosstab(localDefs, responses, 'q-rate', 'q-gender');
    expect(result.rows.map((r) => r.bucket)).toEqual(['3', '5']);
    expect(cellAt(result.rows, '5', 0)).toBe(1); // 5 x f
    expect(cellAt(result.rows, '5', 1)).toBe(1); // 5 x m
    expect(cellAt(result.rows, '3', 0)).toBe(1); // 3 x f
  });
});
