/**
 * Crosstab (contingency table) aggregator — fully client-side.
 *
 * Crosses a row-question against a col-question by joining over the responses that answered
 * BOTH questions. Each response carries every question's answer, so this is a pure in-memory
 * join — no backend support needed.
 *
 * Answer bucketing (via `getAnswerBuckets`):
 * - Multi-value answers (checkbox / multiple-choice) contribute to EACH selected value bucket
 *   on the relevant axis.
 * - Numeric answers bucket by their value (stringified); date / choice / text by stringValue.
 * Buckets that never co-occur are omitted (the matrix only lists buckets that actually appear).
 */
import type { CompletedQuestionerDto } from '@/server/autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import { isValueDefined } from '@/utils/is';

import { getAnswerBuckets, getQuestionId, getQuestionName, getQuestions } from './analyticsTally';

import type { CrosstabCell, CrosstabRow, CrosstabStats } from './analyticsTypes';

const EMPTY_CROSSTAB: CrosstabStats = {
  rowQuestionId: '',
  rowQuestionName: '',
  colQuestionId: '',
  colQuestionName: '',
  colBuckets: [],
  rows: [],
  colTotals: [],
  matchedResponses: 0,
};

function findQuestion(questions: Question[], questionId: string): Question | undefined {
  return questions.find((q) => getQuestionId(q) === questionId);
}

/** Buckets a single response selected for one question id (empty when unanswered). */
function bucketsFor(response: CompletedQuestionerDto, questionId: string): string[] {
  const answered = getQuestions(response).find((q) => getQuestionId(q) === questionId);
  if (!isValueDefined(answered)) return [];
  return getAnswerBuckets(answered.answer, answered.type);
}

/** Accumulates one response's (row bucket × col bucket) co-occurrences into the count map. */
function addCoOccurrences(
  counts: Map<string, Map<string, number>>,
  colBuckets: Set<string>,
  rowVals: string[],
  colVals: string[],
): void {
  for (const rowVal of rowVals) {
    const colMap = counts.get(rowVal) ?? new Map<string, number>();
    for (const colVal of colVals) {
      colBuckets.add(colVal);
      colMap.set(colVal, (colMap.get(colVal) ?? 0) + 1);
    }
    counts.set(rowVal, colMap);
  }
}

function buildRows(
  counts: Map<string, Map<string, number>>,
  orderedCols: string[],
): { rows: CrosstabRow[]; colTotals: number[] } {
  const colTotals = orderedCols.map(() => 0);
  const rows: CrosstabRow[] = Array.from(counts.keys())
    .sort((a, b) => a.localeCompare(b))
    .map((bucket) => {
      const colMap = counts.get(bucket) ?? new Map<string, number>();
      const cells: CrosstabCell[] = orderedCols.map((col, index) => {
        const count = colMap.get(col) ?? 0;
        colTotals[index] += count;
        return { count };
      });
      const total = cells.reduce((acc, cell) => acc + cell.count, 0);
      return { bucket, cells, total };
    });
  return { rows, colTotals };
}

interface JoinResult {
  counts: Map<string, Map<string, number>>;
  colBuckets: Set<string>;
  matchedResponses: number;
}

/** Join the responses that answered both questions into a (row × col) co-occurrence count map. */
function joinResponses(
  responses: CompletedQuestionerDto[],
  rowQuestionId: string,
  colQuestionId: string,
): JoinResult {
  const counts = new Map<string, Map<string, number>>();
  const colBuckets = new Set<string>();
  let matchedResponses = 0;

  for (const response of responses) {
    const rowVals = bucketsFor(response, rowQuestionId);
    const colVals = bucketsFor(response, colQuestionId);
    const answeredBoth = rowVals.length > 0 && colVals.length > 0;
    if (!answeredBoth) continue;
    matchedResponses += 1;
    addCoOccurrences(counts, colBuckets, rowVals, colVals);
  }

  return { counts, colBuckets, matchedResponses };
}

/**
 * Build the crosstab for a row-question id × col-question id over the matching responses.
 * Returns an empty result when either question is missing or the ids are equal.
 */
export function computeCrosstab(
  questions: Question[],
  responses: CompletedQuestionerDto[],
  rowQuestionId: string,
  colQuestionId: string,
): CrosstabStats {
  const rowQuestion = findQuestion(questions, rowQuestionId);
  const colQuestion = findQuestion(questions, colQuestionId);
  const bothFound = isValueDefined(rowQuestion) && isValueDefined(colQuestion);
  const isValidPair = bothFound && rowQuestionId !== colQuestionId;
  if (!isValidPair) return EMPTY_CROSSTAB;

  const { counts, colBuckets, matchedResponses } = joinResponses(responses, rowQuestionId, colQuestionId);
  const orderedCols = Array.from(colBuckets).sort((a, b) => a.localeCompare(b));
  const { rows, colTotals } = buildRows(counts, orderedCols);

  return {
    rowQuestionId,
    rowQuestionName: getQuestionName(rowQuestion),
    colQuestionId,
    colQuestionName: getQuestionName(colQuestion),
    colBuckets: orderedCols,
    rows,
    colTotals,
    matchedResponses,
  };
}
