/**
 * Completion / answered-rate funnel aggregator — fully client-side.
 *
 * IMPORTANT — THIS IS NOT AN ABANDONMENT DROP-OFF FUNNEL.
 * Only COMPLETED submissions are stored (each response carries a CompletedDate only; there
 * is no partial/abandoned record). We therefore CANNOT measure true mid-survey abandonment.
 * What this funnel measures instead, over the set of completed responses:
 *   (a) per-question answered-rate: how often each question actually had a non-null/non-empty
 *       answer (questions can be optional or skipped by skip logic), and
 *   (b) per-page reach: how many responses answered at least one question on each page —
 *       a proxy for how far `page` + `skipConditions` let respondents progress.
 * True drop-off requires a backend partial-progress capture and is out of scope.
 */
import type { CompletedQuestionerDto } from '@/server/autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import { isValueDefined } from '@/utils/is';

import { getQuestionId, getQuestionName, getQuestions, hasAnswer } from './analyticsTally';

import type { FunnelPageStep, FunnelQuestionStep, FunnelStats } from './analyticsTypes';

const PERCENT_MULTIPLIER = 100;
const DEFAULT_PAGE = 0;

const EMPTY_FUNNEL: FunnelStats = {
  totalResponses: 0,
  questionSteps: [],
  pageSteps: [],
};

function pct(part: number, total: number): number {
  return total > 0 ? (part / total) * PERCENT_MULTIPLIER : 0;
}

function getPage(question: Question): number {
  return typeof question.page === 'number' ? question.page : DEFAULT_PAGE;
}

/** Count how many responses gave a meaningful answer to a single question. */
function countAnswered(question: Question, responses: CompletedQuestionerDto[]): number {
  const questionId = getQuestionId(question);
  let answered = 0;
  for (const response of responses) {
    const match = getQuestions(response).find((q) => getQuestionId(q) === questionId);
    if (isValueDefined(match) && hasAnswer(match.answer, match.type)) answered += 1;
  }
  return answered;
}

function buildQuestionSteps(
  questions: Question[],
  responses: CompletedQuestionerDto[],
  total: number,
): FunnelQuestionStep[] {
  return questions.map((question) => {
    const answered = countAnswered(question, responses);
    return {
      questionId: getQuestionId(question),
      questionName: getQuestionName(question),
      page: getPage(question),
      answered,
      total,
      answeredPct: pct(answered, total),
    };
  });
}

/** Count responses that answered at least one question on a given page. */
function countPageReached(
  pageQuestionIds: Set<string>,
  responses: CompletedQuestionerDto[],
): number {
  let reached = 0;
  for (const response of responses) {
    const hit = getQuestions(response).some(
      (q) => pageQuestionIds.has(getQuestionId(q)) && hasAnswer(q.answer, q.type),
    );
    if (hit) reached += 1;
  }
  return reached;
}

function buildPageSteps(
  questions: Question[],
  responses: CompletedQuestionerDto[],
  total: number,
): FunnelPageStep[] {
  const byPage = new Map<number, Set<string>>();
  for (const question of questions) {
    const page = getPage(question);
    const ids = byPage.get(page) ?? new Set<string>();
    ids.add(getQuestionId(question));
    byPage.set(page, ids);
  }

  return Array.from(byPage.keys())
    .sort((a, b) => a - b)
    .map((page) => {
      const reached = countPageReached(byPage.get(page) ?? new Set<string>(), responses);
      return { page, reached, total, reachedPct: pct(reached, total) };
    });
}

/**
 * Compute the completion / answered-rate funnel over the given completed responses.
 * NOT abandonment drop-off — see the file header for the caveat.
 */
export function computeFunnel(
  questions: Question[],
  responses: CompletedQuestionerDto[],
): FunnelStats {
  if (questions.length === 0) return EMPTY_FUNNEL;
  const total = responses.length;
  return {
    totalResponses: total,
    questionSteps: buildQuestionSteps(questions, responses, total),
    pageSteps: buildPageSteps(questions, responses, total),
  };
}
