import type { Question as ApiQuestionModel } from '@/server/autoGeneratedHooks/questioner/models';

import { mergeDraftAnswers } from './mergeDraftAnswers';


function q(id: string, answer?: ApiQuestionModel['answer']): ApiQuestionModel {
  const question: ApiQuestionModel = { id, name: id, page: 1, order: 1, answer };
  return question;
}

describe('mergeDraftAnswers', () => {
  it('returns template questions unchanged when no draft answers', () => {
    const tpl = [q('a'), q('b')];
    expect(mergeDraftAnswers(tpl, undefined)).toBe(tpl);
    expect(mergeDraftAnswers(tpl, [])).toBe(tpl);
  });

  it('merges draft answers by question id', () => {
    const tpl = [q('a'), q('b')];
    const draft = [q('a', { stringValue: 'hi' })];
    const merged = mergeDraftAnswers(tpl, draft);
    expect(merged[0].answer).toEqual({ stringValue: 'hi' });
    expect(merged[1].answer).toBeUndefined();
  });

  it('ignores draft answers for unknown ids', () => {
    const tpl = [q('a')];
    const draft = [q('zzz', { stringValue: 'x' })];
    const merged = mergeDraftAnswers(tpl, draft);
    expect(merged[0].answer).toBeUndefined();
  });

  it('does not mutate the input questions', () => {
    const tpl = [q('a')];
    mergeDraftAnswers(tpl, [q('a', { stringValue: 'hi' })]);
    expect(tpl[0].answer).toBeUndefined();
  });
});
