import type { Question as ApiQuestionModel } from '@/server/autoGeneratedHooks/questioner/models';
import { isValueDefined } from '@/utils/is';


export function mergeDraftAnswers(
  templateQuestions: ApiQuestionModel[],
  draftQuestions: ApiQuestionModel[] | undefined | null,
): ApiQuestionModel[] {
  if (!isValueDefined(draftQuestions) || draftQuestions.length === 0) return templateQuestions;

  const answersById = new Map<string, ApiQuestionModel['answer']>();
  for (const q of draftQuestions) 
    if (isValueDefined(q.id) && isValueDefined(q.answer)) answersById.set(q.id, q.answer);
  

  return templateQuestions.map((q) =>
    isValueDefined(q.id) && answersById.has(q.id) ? { ...q, answer: answersById.get(q.id) } : q,
  );
}

interface HasQuestions {
  contents?: { questions?: ApiQuestionModel[] } | null;
}

export function mergeDraftIntoTemplate<T extends HasQuestions>(
  data: T | undefined,
  draftQuestions: ApiQuestionModel[] | undefined | null,
): T | undefined {
  const templateQuestions = data?.contents?.questions;
  if (!isValueDefined(data) || !isValueDefined(templateQuestions)) return data;
  if (!isValueDefined(draftQuestions) || draftQuestions.length === 0) return data;
  return { ...data, contents: { ...data.contents, questions: mergeDraftAnswers(templateQuestions, draftQuestions) } };
}
