import type { Question as ApiQuestionModel } from '@/server/autoGeneratedHooks/questioner/models';
import { isValueDefined } from '@/utils/is';


/**
 * Merges a respondent's saved draft answers into the template's questions (matched
 * by question id) so a resumed survey renders prefilled. Returns the original
 * template questions unchanged when there are no draft answers. Pure — no mutation
 * of the inputs.
 */
export function mergeDraftAnswers(
  templateQuestions: ApiQuestionModel[],
  draftQuestions: ApiQuestionModel[] | undefined | null,
): ApiQuestionModel[] {
  if (!isValueDefined(draftQuestions) || draftQuestions.length === 0) return templateQuestions;

  const answersById = new Map<string, ApiQuestionModel['answer']>();
  for (const q of draftQuestions) 
    if (isValueDefined(q.id) && isValueDefined(q.answer)) answersById.set(q.id, q.answer);
  

  return templateQuestions.map((q) =>
    isValueDefined(q.id) && answersById.has(q.id) ? { ...q, answer: answersById.get(q.id) } : q,
  );
}

/** Shape carrying the respondent-facing questions, common to the template DTO. */
interface HasQuestions {
  contents?: { questions?: ApiQuestionModel[] } | null;
}

/**
 * Returns a copy of the template data with the draft's saved answers merged into
 * its questions, or the original data when there is nothing to merge.
 */
export function mergeDraftIntoTemplate<T extends HasQuestions>(
  data: T | undefined,
  draftQuestions: ApiQuestionModel[] | undefined | null,
): T | undefined {
  const templateQuestions = data?.contents?.questions;
  if (!isValueDefined(data) || !isValueDefined(templateQuestions)) return data;
  if (!isValueDefined(draftQuestions) || draftQuestions.length === 0) return data;
  return { ...data, contents: { ...data.contents, questions: mergeDraftAnswers(templateQuestions, draftQuestions) } };
}
