/**
 * Helper functions for quiz-active page.
 * Extracted to reduce component size and improve maintainability.
 */
import { QuestionType } from '../../../components/DynamicForm';
import { asFileReferences } from '../../../components/DynamicForm/questionTypes/fileUploadHelpers';
import { getEntryByApiType, getEntryByUiType } from '../../../components/DynamicForm/questionTypes/registry';
import { isRequiredAnswerMissing } from '../../../components/DynamicForm/questionTypes/validation';
import { isValueDefined } from '../../../utils/is';


import type { DynamicQuiz, Answer, Question as UiQuestion, QuestionConfig, ValidationRules } from '../../../components/DynamicForm';
import type {
  Question as ApiQuestionModel,
  QuestionType as ApiQuestionTypeT,
  Option as ApiOption,
  SkipCondition as ApiSkipCondition,
  QuestionConfig as ApiQuestionConfig,
  ValidationRules as ApiValidationRules,
  CreateCompletedQuestionerRequest,
  FileReference,
} from '../../../server/autoGeneratedHooks/questioner/models';

export { isRequiredAnswerMissing } from '../../../components/DynamicForm/questionTypes/validation';

type ApiAnswerPayload =
  | { boolValue: boolean }
  | { numericValue: number }
  | { stringValue: string }
  | { multiValues: string[] }
  | { files: FileReference[] };

export function apiToUiType(typeValue: number | undefined): QuestionType {
  return getEntryByApiType(typeValue).uiType;
}

export function uiToApiType(typeValue: QuestionType): ApiQuestionTypeT {
  return getEntryByUiType(typeValue).apiType;
}

export function shouldSkipForForm(form: DynamicQuiz, question: UiQuestion): boolean {
  if (!Array.isArray(question.skipConditions) || question.skipConditions.length === 0) return false;
  return question.skipConditions.some((condition) => {
    const trigger = form.questions.find((q) => q.id === condition.questionId);
    if (!isValueDefined(trigger)) return false;
    const answer = trigger.answer;
    if (!isValueDefined(answer)) return false;
    if (Array.isArray(answer)) 
      return answer.some((v) => String(v) === String(condition.questionAnswer));
    
    return String(answer) === String(condition.questionAnswer);
  });
}

export function pageHasVisibleQuestion(form: DynamicQuiz, page: number): boolean {
  return form.questions.some((q) => q.page === page && !shouldSkipForForm(form, q));
}

export function getOrderedPages(form: DynamicQuiz): number[] {
  return [...new Set(form.questions.map((q) => q.page))].sort((a, b) => a - b);
}

export function findPageInDirection(form: DynamicQuiz, startPage: number, direction: 1 | -1): number | null {
  const orderedPages = getOrderedPages(form);
  if (direction > 0) 
    for (const page of orderedPages) {
      if (page > startPage && pageHasVisibleQuestion(form, page)) 
        return page;
      
    }
   else 
    for (let idx = orderedPages.length - 1; idx >= 0; idx -= 1) {
      const page = orderedPages[idx];
      if (page < startPage && pageHasVisibleQuestion(form, page)) 
        return page;
      
    }
  
  return null;
}

export function isPageComplete(form: DynamicQuiz, page: number): boolean {
  const questionsOnPage = form.questions.filter((q) => q.page === page);
  const hasMissing = questionsOnPage.some((q) => {
    if (shouldSkipForForm(form, q)) return false;
    if (q.isRequired !== true) return false;
    return isRequiredAnswerMissing(q.answer);
  });
  return !hasMissing;
}

export function toApiAnswer(value: Answer | undefined): ApiAnswerPayload | null {
  if (!isValueDefined(value)) return null;
  if (typeof value === 'boolean') return { boolValue: value };
  if (typeof value === 'number') return { numericValue: value };
  if (typeof value === 'string') return { stringValue: value };
  if (Array.isArray(value)) {
    const files = asFileReferences(value);
    if (files.length > 0) return { files };
    return { multiValues: value.map((x) => String(x)) };
  }
  return null;
}

function mapApiConfigToUi(config: ApiQuestionConfig | null | undefined): QuestionConfig | undefined {
  if (!isValueDefined(config)) return undefined;
  const out: QuestionConfig = {};
  if (isValueDefined(config.scaleMin)) out.scaleMin = config.scaleMin;
  if (isValueDefined(config.scaleMax)) out.scaleMax = config.scaleMax;
  if (isValueDefined(config.scaleStep)) out.scaleStep = config.scaleStep;
  if (isValueDefined(config.minLabel)) out.minLabel = config.minLabel;
  if (isValueDefined(config.maxLabel)) out.maxLabel = config.maxLabel;
  if (isValueDefined(config.allowedContentTypes)) out.allowedContentTypes = config.allowedContentTypes;
  if (isValueDefined(config.maxSizeBytes)) out.maxSizeBytes = config.maxSizeBytes;
  if (isValueDefined(config.maxFiles)) out.maxFiles = config.maxFiles;
  return Object.keys(out).length > 0 ? out : undefined;
}

function mapApiRulesToUi(rules: ApiValidationRules | null | undefined): ValidationRules | undefined {
  if (!isValueDefined(rules)) return undefined;
  const out: ValidationRules = {};
  if (isValueDefined(rules.minLength)) out.minLength = rules.minLength;
  if (isValueDefined(rules.maxLength)) out.maxLength = rules.maxLength;
  if (isValueDefined(rules.pattern)) out.pattern = rules.pattern;
  if (isValueDefined(rules.patternMessage)) out.patternMessage = rules.patternMessage;
  if (isValueDefined(rules.min)) out.min = rules.min;
  if (isValueDefined(rules.max)) out.max = rules.max;
  if (isValueDefined(rules.minSelections)) out.minSelections = rules.minSelections;
  if (isValueDefined(rules.maxSelections)) out.maxSelections = rules.maxSelections;
  return Object.keys(out).length > 0 ? out : undefined;
}

export function mapApiQuestionToUi(q: ApiQuestionModel, idx: number): UiQuestion {
  const apiTypeNum: number | undefined = typeof q.type === 'number' ? q.type : undefined;
  let uiType = apiToUiType(apiTypeNum);
  // Heuristic: if server says Text but provides options, treat as dropdown for better UX
  if (uiType === QuestionType.Text && (q.options?.length ?? 0) > 0)
    uiType = QuestionType.Dropdown;
  
  const pageRaw = q.page ?? 1;
  const pageUi = pageRaw <= 0 ? 1 : pageRaw; // normalize 0-based to 1-based
  return {
    id: q.id ?? `q_${idx}`,
    name: q.name ?? '',
    type: uiType,
    options: (q.options ?? [])
      .filter(Boolean)
      .map((opt: ApiOption) => ({ label: String(opt.label ?? ''), value: String(opt.value ?? '') })),
    page: pageUi,
    answer: undefined,
    isRequired: Boolean(q.isRequired),
    skipConditions: (q.skipConditions ?? [])
      .filter(Boolean)
      .map((sc: ApiSkipCondition) => ({
        questionId: String(sc.questionId ?? ''),
        questionAnswer: String(sc.questionAnswer ?? ''),
      })),
    order: q.order ?? idx + 1,
    config: mapApiConfigToUi(q.config),
    validationRules: mapApiRulesToUi(q.validationRules),
  };
}

function toApiQuestion(q: UiQuestion): ApiQuestionModel {
  return {
    id: q.id,
    name: q.name,
    type: uiToApiType(q.type),
    options: (q.options ?? []).map((o) => ({ label: o.label, value: String(o.value) })),
    page: q.page,
    answer: toApiAnswer(q.answer),
    isRequired: q.isRequired ?? false,
    skipConditions: (q.skipConditions ?? []).map((sc) => ({
      questionId: sc.questionId,
      questionAnswer: String(sc.questionAnswer),
    })),
    order: q.order,
    config: q.config ?? null,
    validationRules: q.validationRules ?? null,
  };
}

export function buildSubmissionPayload(
  form: DynamicQuiz,
  tpl: { name?: string | null; description?: string | null; externalId?: string | null }
): CreateCompletedQuestionerRequest {
  return {
    name: tpl.name ?? form.name,
    description: tpl.description ?? form.description ?? null,
    questionerTemplateExternalId: tpl.externalId ?? undefined,
    contents: { questions: form.questions.map(toApiQuestion) },
  };
}
