/**
 * Tests for quizHelpers - Type conversion functions.
 */
import { apiToUiType, uiToApiType } from './quizHelpers';
import { QuestionType as ApiQuestionType } from '../../../server/autoGeneratedHooks/questioner/models/questionType';
import QuestionType from '../../../shared/enums/QuestionType';

describe('quizHelpers - Type Conversion', () => {
  describe('apiToUiType', () => {
    it('returns "text" for undefined', () => {
      expect(apiToUiType(undefined)).toBe('text');
    });

    it('returns "multiple-choice" for MultipleChoice enum', () => {
      expect(apiToUiType(ApiQuestionType.MultipleChoice)).toBe('multiple-choice');
    });

    it('returns "checkbox" for Checkbox enum', () => {
      expect(apiToUiType(ApiQuestionType.Checkbox)).toBe('checkbox');
    });

    it('returns "radio" for Radio enum', () => {
      expect(apiToUiType(ApiQuestionType.Radio)).toBe('radio');
    });

    it('returns "dropdown" for Dropdown enum', () => {
      expect(apiToUiType(ApiQuestionType.Dropdown)).toBe('dropdown');
    });

    it('returns "text" for Text enum', () => {
      expect(apiToUiType(ApiQuestionType.Text)).toBe('text');
    });

    it('returns "rating" for Rating enum', () => {
      expect(apiToUiType(ApiQuestionType.Rating)).toBe('rating');
    });

    it('returns "nps" for Nps enum', () => {
      expect(apiToUiType(ApiQuestionType.Nps)).toBe('nps');
    });

    it('returns "number" for Number enum', () => {
      expect(apiToUiType(ApiQuestionType.Number)).toBe('number');
    });

    it('returns "date" for Date enum', () => {
      expect(apiToUiType(ApiQuestionType.Date)).toBe('date');
    });

    it('returns "linear-scale" for LinearScale enum', () => {
      expect(apiToUiType(ApiQuestionType.LinearScale)).toBe('linear-scale');
    });

    it('returns "text" for unknown values', () => {
      expect(apiToUiType(999)).toBe('text');
    });
  });

  describe('uiToApiType', () => {
    it('returns MultipleChoice for "multiple-choice"', () => {
      expect(uiToApiType(QuestionType.MultipleChoice)).toBe(ApiQuestionType.MultipleChoice);
    });

    it('returns Checkbox for "checkbox"', () => {
      expect(uiToApiType(QuestionType.Checkbox)).toBe(ApiQuestionType.Checkbox);
    });

    it('returns Radio for "radio"', () => {
      expect(uiToApiType(QuestionType.Radio)).toBe(ApiQuestionType.Radio);
    });

    it('returns Dropdown for "dropdown"', () => {
      expect(uiToApiType(QuestionType.Dropdown)).toBe(ApiQuestionType.Dropdown);
    });

    it('returns Text for "text"', () => {
      expect(uiToApiType(QuestionType.Text)).toBe(ApiQuestionType.Text);
    });

    it('returns Rating for "rating"', () => {
      expect(uiToApiType(QuestionType.Rating)).toBe(ApiQuestionType.Rating);
    });

    it('returns Nps for "nps"', () => {
      expect(uiToApiType(QuestionType.Nps)).toBe(ApiQuestionType.Nps);
    });

    it('returns Number for "number"', () => {
      expect(uiToApiType(QuestionType.Number)).toBe(ApiQuestionType.Number);
    });

    it('returns Date for "date"', () => {
      expect(uiToApiType(QuestionType.Date)).toBe(ApiQuestionType.Date);
    });

    it('returns LinearScale for "linear-scale"', () => {
      expect(uiToApiType(QuestionType.LinearScale)).toBe(ApiQuestionType.LinearScale);
    });
  });

  describe('round-trip', () => {
    it('preserves every UI type through api and back', () => {
      const all = [
        QuestionType.Text, QuestionType.MultipleChoice, QuestionType.Checkbox,
        QuestionType.Radio, QuestionType.Dropdown, QuestionType.Rating,
        QuestionType.Nps, QuestionType.Number, QuestionType.Date, QuestionType.LinearScale,
      ];
      all.forEach((uiType) => {
        expect(apiToUiType(uiToApiType(uiType))).toBe(uiType);
      });
    });
  });
});
