import React from 'react';

import { ScrollView, StyleSheet, View, useWindowDimensions } from 'react-native';

import TemplateLivePreview from './TemplateLivePreview';
import { TWO_PANE_MIN_WIDTH_PX } from '../../../shared/constants';

import type { Question } from '../../../server/autoGeneratedHooks/questioner/models/question';

const EDITOR_PANE_FLEX = 58;
const PREVIEW_PANE_FLEX = 42;
const PANE_GAP_PX = 24;
const PANE_VERTICAL_OFFSET_PX = 176;

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    gap: PANE_GAP_PX,
  },
  editorPane: {
    flex: EDITOR_PANE_FLEX,
  },
  previewPane: {
    flex: PREVIEW_PANE_FLEX,
  },
});

interface Props {
  name: string;
  description: string;
  questions: Question[];
  children: React.ReactNode;
}

const TemplateEditorPanes = ({ name, description, questions, children }: Props): React.ReactNode => {
  const { width, height } = useWindowDimensions();
  const isWide = width >= TWO_PANE_MIN_WIDTH_PX;

  if (!isWide) return children;

  const paneHeight = Math.max(height - PANE_VERTICAL_OFFSET_PX, 0);

  return (
    <View style={[styles.row, { height: paneHeight }]}>
      <ScrollView style={styles.editorPane}>{children}</ScrollView>
      <View style={styles.previewPane}>
        <TemplateLivePreview description={description} name={name} questions={questions} />
      </View>
    </View>
  );
};

export default TemplateEditorPanes;
