import React from 'react';

import { View, Text } from 'react-native';


import CancelButton from '@/components/Buttons/CancelButton';
import SaveButton from '@/components/Buttons/SaveButton';
import ActionRow from '@/components/core/ActionRow/ActionRow';
import Section from '@/components/Shared/Section';
import { FM } from '@/localization/helpers';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import type RespondentContactMode from '@/shared/enums/RespondentContactMode';
import { useTheme } from '@/theme/hooks/useTheme';
import { layoutStyles } from '@/theme/utils/styles';


import QuestionList from './Editor/QuestionList';
import TemplateAvailabilityFields from './TemplateAvailabilityFields';
import TemplateForm from './TemplateForm';

interface Props {
  name: string;
  description: string;
  isActive: boolean;
  onChange: (payload: { name: string; description: string; isActive: boolean }) => void;
  questions: Question[];
  onQuestionsChange: (qs: Question[]) => void;
  onSave: () => void;
  onCancel: () => void;
  saving?: boolean;
  enableAnswerSection: boolean;
  readOnly?: boolean;
  /** Unique key to force TemplateForm remount when editing a different item */
  itemKey?: string;
  /** Date-only (YYYY-MM-DD) raw input for the soft-closing date. */
  closingDate: string;
  /** Raw numeric-text input for the response quota. */
  maxResponses: string;
  /** Respondent identity collection mode. */
  respondentContactMode: RespondentContactMode;
  onClosingDateChange: (value: string) => void;
  onMaxResponsesChange: (value: string) => void;
  onRespondentContactModeChange: (mode: RespondentContactMode) => void;
}

const TemplateEditorForm = ({
  name,
  description,
  isActive,
  onChange,
  questions,
  onQuestionsChange,
  onSave,
  onCancel,
  saving = false,
  enableAnswerSection,
  readOnly = false,
  itemKey,
  closingDate,
  maxResponses,
  respondentContactMode,
  onClosingDateChange,
  onMaxResponsesChange,
  onRespondentContactModeChange,
}: Props): React.ReactElement => {
  const { theme } = useTheme();
  const colors = theme.colors;

  const questionsLabelStyle = React.useMemo(
    () => [layoutStyles.questionsLabel, { color: colors.text }],
    [colors.text],
  );

  return (
    <Section style={layoutStyles.sectionSpacing}>
      <TemplateForm
        key={itemKey}
        showStatus
        hideActions={readOnly}
        initialDescription={description}
        initialIsActive={isActive}
        initialName={name}
        saving={saving}
        onCancel={onCancel}
        onChange={({ name: n, description: d, isActive: a }) => onChange({ name: n, description: d, isActive: a })}
        onSave={onSave}
      />

      <TemplateAvailabilityFields
        closingDate={closingDate}
        maxResponses={maxResponses}
        readOnly={readOnly}
        respondentContactMode={respondentContactMode}
        onClosingDateChange={onClosingDateChange}
        onMaxResponsesChange={onMaxResponsesChange}
        onRespondentContactModeChange={onRespondentContactModeChange}
      />

      <View style={layoutStyles.questionsWrapper}>
        <Text style={questionsLabelStyle}>{FM('quizTemplates.questions')}</Text>
        <Text style={layoutStyles.questionsSubLabel}>
          {FM('quizTemplates.questionsLabelHelp')}
        </Text>
        <QuestionList enableAnswerSection={enableAnswerSection} questions={questions} onChange={onQuestionsChange} />
      </View>

      {!readOnly ? (
        <View style={layoutStyles.actionRowWrapper}>
          <ActionRow>
            <SaveButton title={FM('quizTemplates.save')} onPress={onSave} />
            <CancelButton title={FM('quizTemplates.cancel')} onPress={onCancel} />
          </ActionRow>
        </View>
      ) : null}
    </Section>
  );
};

export default TemplateEditorForm;
