import React, { useMemo } from 'react';

import { StyleSheet, Text, View } from 'react-native';

import QuizContent from '../../../../app/(protected)/quiz-active/QuizContent';
import { useQuizForm } from '../../../hooks/quiz';
import { FM } from '../../../localization/helpers';
import { TestIds } from '../../../shared/testIds';
import { useTheme } from '../../../theme/hooks/useTheme';
import { useDynamicFormStyles } from '../../../theme/utils/styles';

import type { Question } from '../../../server/autoGeneratedHooks/questioner/models/question';

const PREVIEW_HEADER_PADDING = 12;
const PREVIEW_LABEL_FONT_SIZE = 13;
const PREVIEW_LABEL_LETTER_SPACING = 0.5;

const previewStyles = StyleSheet.create({
  wrapper: {
    flex: 1,
  },
  header: {
    paddingBottom: PREVIEW_HEADER_PADDING,
    marginBottom: PREVIEW_HEADER_PADDING,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  label: {
    fontSize: PREVIEW_LABEL_FONT_SIZE,
    fontWeight: '600',
    letterSpacing: PREVIEW_LABEL_LETTER_SPACING,
    textTransform: 'uppercase',
  },
});

const NOOP_SUBMIT = { mutateAsync: async (): Promise<void> => { await Promise.resolve(); } };

async function noopRefetch(): Promise<void> {
  await Promise.resolve();
}

interface Props {
  name: string;
  description: string;
  questions: Question[];
}

const TemplateLivePreview = ({ name, description, questions }: Props): React.ReactElement => {
  const { theme } = useTheme();
  const colors = theme.colors;
  const styles = useDynamicFormStyles();

  const previewData = useMemo(
    () => ({ externalId: 'template-preview', name, description, contents: { questions } }),
    [name, description, questions],
  );
  const quizOptions = useMemo(() => ({ t: FM }), []);
  const quizForm = useQuizForm(previewData, NOOP_SUBMIT, noopRefetch, quizOptions);

  const headerStyle = useMemo(
    () => [previewStyles.header, { borderBottomColor: colors.border }],
    [colors.border],
  );
  const labelStyle = useMemo(
    () => [previewStyles.label, { color: colors.textSecondary }],
    [colors.textSecondary],
  );

  return (
    <View style={previewStyles.wrapper} testID={TestIds.TEMPLATE_EDITOR_LIVE_PANE}>
      <View style={headerStyle}>
        <Text accessibilityRole="header" style={labelStyle}>
          {FM('quizTemplates.livePreview')}
        </Text>
      </View>

      {quizForm.form ? (
        <QuizContent
          currentPage={quizForm.currentPage}
          currentQuestions={quizForm.currentQuestions}
          errors={quizForm.errors}
          form={quizForm.form}
          handleBack={quizForm.handleBack}
          handleNext={quizForm.handleNext}
          pageOpacity={quizForm.pageOpacity}
          scrollRef={quizForm.scrollRef}
          shouldSkip={quizForm.shouldSkip}
          styles={styles}
          submitting={quizForm.submitting}
          totalPages={quizForm.totalPages}
          updateAnswer={quizForm.updateAnswer}
        />
      ) : null}
    </View>
  );
};

export default TemplateLivePreview;
