const path = require('path');
const { getDefaultConfig } = require('expo/metro-config');

const projectRoot = __dirname;

const config = getDefaultConfig(projectRoot);
const fs = require('fs');

// Don't watch the entire workspace root — it includes SyncfusionThemeStudio,
// E2ETests, Services, etc. whose Playwright test-results dirs crash Metro's
// FallbackWatcher on Windows (ENOENT / UNKNOWN lstat errors from transient
// artifact directories). All packages are under BaseClient/packages/ (resolved
// via extraNodeModules), so no external watchFolders are needed.

// Exclude build output directories from Metro's file watcher.
// On Windows, Metro's FallbackWatcher (used when Watchman is absent) follows
// symlinks inside these dirs and produces UNKNOWN lstat errors when
// unstable_enableSymlinks:true causes it to construct self-referential paths
// like `dist\?\C:\...\dist`. Blocking them prevents the crash.
const blockListPatterns = [
  path.join(projectRoot, 'dist'),
  path.join(projectRoot, 'coverage'),
  path.join(projectRoot, 'lighthouse-reports'),
].map((p) => new RegExp(`^${p.replace(/\\/g, '\\\\').replace(/\//g, '[\\\\/]')}.*`));

// Path to host app's React modules - these must be used by all packages
const hostReactPath = path.join(projectRoot, 'node_modules', 'react');
const hostReactDomPath = path.join(projectRoot, 'node_modules', 'react-dom');

config.resolver = {
  ...config.resolver,
  unstable_enableSymlinks: true,
  unstable_enablePackageExports: true,
  blockList: blockListPatterns,
  nodeModulesPaths: [
    path.join(projectRoot, 'node_modules'),
  ],
  extraNodeModules: {
    // Micro-frontend module packages
    '@baseclient/core': path.join(projectRoot, 'packages', 'core', 'src'),
    '@baseclient/identity-module': path.join(projectRoot, 'packages', 'identity-module', 'src'),
    '@baseclient/questioner-module': path.join(projectRoot, 'packages', 'questioner-module', 'src'),
    '@baseclient/onlinemenu-module': path.join(projectRoot, 'packages', 'onlinemenu-module', 'src'),
    '@onlinemenu/identity-client': path.join(projectRoot, 'packages', 'identity-client', 'dist'),
  },
  // Custom resolver to force React to always resolve from host app
  resolveRequest: (context, moduleName, platform) => {
    // Resolve @/ alias to src/ directory
    if (typeof moduleName === 'string' && moduleName.startsWith('@/')) {
      const subPath = moduleName.slice(2);
      const basePath = path.join(projectRoot, 'src', subPath);
      // Try common extensions to find the actual file
      for (const ext of ['.ts', '.tsx', '.js', '.jsx', '.json', '/index.ts', '/index.tsx', '/index.js']) {
        const filePath = basePath + ext;
        if (fs.existsSync(filePath)) {
          return { filePath, type: 'sourceFile' };
        }
      }
    }
    // Force all React imports to use the host app's React
    // This prevents duplicate React instances from linked packages
    if (moduleName === 'react' || moduleName.startsWith('react/')) {
      return {
        filePath: moduleName === 'react'
          ? path.join(hostReactPath, 'index.js')
          : path.join(hostReactPath, moduleName.replace('react/', '') + '.js'),
        type: 'sourceFile',
      };
    }
    if (moduleName === 'react-dom' || moduleName.startsWith('react-dom/')) {
      return {
        filePath: moduleName === 'react-dom'
          ? path.join(hostReactDomPath, 'index.js')
          : path.join(hostReactDomPath, moduleName.replace('react-dom/', '') + '.js'),
        type: 'sourceFile',
      };
    }
    // Handle case-insensitive matches for autoGeneratedHooks imports
    if (typeof moduleName === 'string' && moduleName.includes('autoGeneratedHooks')) {
      try {
        const rel = moduleName.replace(/^\.?\/?/, '');
        const absDir = path.resolve(projectRoot, path.dirname(rel));
        const requestedBase = path.basename(rel);
        if (fs.existsSync(absDir)) {
          const children = fs.readdirSync(absDir);
          const match = children.find((c) => c.toLowerCase().startsWith(requestedBase.toLowerCase()));
          if (match) {
            const normalized = path.join(path.dirname(rel), match).replace(/\\/g, '/');
            return context.resolveRequest(context, normalized, platform);
          }
        }
      } catch {
        // ignore and continue
      }
    }
    // Default resolution
    return context.resolveRequest(context, moduleName, platform);
  },
};

module.exports = config;
