import type { DisplayPreference as AutoDisplayPreference } from '../../../server/autoGeneratedHooks/notification/models';

export type DisplayPreference = AutoDisplayPreference;

export interface CategoryPreference {
  enabled: boolean;
  displayPreference: DisplayPreference;
}

export interface NotificationPreferences {
  notificationsEnabled: boolean;
  quietHoursEnabled: boolean;
  quietHoursStart: string | null;
  quietHoursEnd: string | null;
  quietHoursTimezone: string | null;
  categoryPreferences: {
    questionnaireSubmitted: CategoryPreference;
    templateUpdated: CategoryPreference;
    userInvited: CategoryPreference;
    menuUpdated: CategoryPreference;
    paymentDue: CategoryPreference;
  };
}

export const DISPLAY_PREFERENCE_OPTIONS = [
  { label: 'None', value: 0 },
  { label: 'In-App', value: 1 },
  { label: 'OS Notification', value: 2 },
  { label: 'Both', value: 3 },
] as const;

export const NOTIFICATION_CATEGORIES = [
  'questionnaireSubmitted',
  'templateUpdated',
  'userInvited',
  'menuUpdated',
  'paymentDue',
] as const;

export type NotificationCategoryKey = typeof NOTIFICATION_CATEGORIES[number];
