/**
 * Prefetches dashboard data into the React Query cache.
 *
 * Call this immediately after a successful login (before navigation) so
 * that by the time the dashboard mounts, the critical API responses are
 * already cached and the user sees content instead of spinners.
 *
 * Uses `queryClient.prefetchQuery` which is fire-and-forget -- failures
 * are silently swallowed since the dashboard hooks will retry on mount.
 *
 * Erevna is the Questioner product. The dashboard never reads
 * online-menu data -- prefetching it would (a) make a wasted network
 * call to onlinemenu-api.dloizides.com, and (b) leak the cross-realm
 * wall (the menu API rejects questioner-realm tokens with 401, which
 * pollutes error monitoring). The menu prefetch was removed as part
 * of the Phase-3 product feature-strip.
 */
import { queryClient } from '@/lib/queryClient';
import {
  getIdentityServiceAPIMeGetBusinessProfileQueryOptions,
  getIdentityServiceAPIMeGetPreferencesQueryOptions,
} from '@/server/autoGeneratedHooks/identity/me/me';
import { getQuestionerWebQuestionerTemplatesListQueryOptions } from '@/server/autoGeneratedHooks/questioner/questionertemplates/questionertemplates';

export function prefetchDashboardData(): void {
  // User preferences (needed by welcome wizard + setup checklist)
  queryClient
    .prefetchQuery(getIdentityServiceAPIMeGetPreferencesQueryOptions())
    .catch(() => undefined);

  // Business profile (needed by setup checklist + profile nudge)
  queryClient
    .prefetchQuery(getIdentityServiceAPIMeGetBusinessProfileQueryOptions())
    .catch(() => undefined);

  // Template list (needed by dashboard cards).
  // Erevna is the Questioner product, so this prefetch is unconditional.
  queryClient
    .prefetchQuery(getQuestionerWebQuestionerTemplatesListQueryOptions())
    .catch(() => undefined);
}
