import { queryClient } from '@/lib/queryClient';
import {
  getIdentityServiceAPIMeGetBusinessProfileQueryOptions,
  getIdentityServiceAPIMeGetPreferencesQueryOptions,
} from '@/server/autoGeneratedHooks/identity/me/me';
import { getQuestionerWebQuestionerTemplatesListQueryOptions } from '@/server/autoGeneratedHooks/questioner/questionertemplates/questionertemplates';

export function prefetchDashboardData(): void {
  queryClient
    .prefetchQuery(getIdentityServiceAPIMeGetPreferencesQueryOptions())
    .catch(() => undefined);

  queryClient
    .prefetchQuery(getIdentityServiceAPIMeGetBusinessProfileQueryOptions())
    .catch(() => undefined);

  queryClient
    .prefetchQuery(getQuestionerWebQuestionerTemplatesListQueryOptions())
    .catch(() => undefined);
}
