import { queryClient } from '@/lib/queryClient';

import { prefetchDashboardData } from './prefetchDashboardData';

jest.mock('@/lib/queryClient', () => ({
  queryClient: {
    prefetchQuery: jest.fn().mockResolvedValue(undefined),
  },
}));

jest.mock('@/server/autoGeneratedHooks/identity/me/me', () => ({
  getIdentityServiceAPIMeGetPreferencesQueryOptions: jest.fn(() => ({ queryKey: ['prefs'] })),
  getIdentityServiceAPIMeGetBusinessProfileQueryOptions: jest.fn(() => ({ queryKey: ['profile'] })),
}));

jest.mock('@/server/autoGeneratedHooks/questioner/questionertemplates/questionertemplates', () => ({
  getQuestionerWebQuestionerTemplatesListQueryOptions: jest.fn(() => ({ queryKey: ['templates'] })),
}));

describe('prefetchDashboardData (Erevna)', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('prefetches preferences, business profile, and template list (3 queries)', () => {
    prefetchDashboardData();

    const EXPECTED_PREFETCH_COUNT = 3;
    expect(queryClient.prefetchQuery).toHaveBeenCalledTimes(EXPECTED_PREFETCH_COUNT);
  });

  it('prefetches preferences query', () => {
    prefetchDashboardData();

    expect(queryClient.prefetchQuery).toHaveBeenCalledWith(
      expect.objectContaining({ queryKey: ['prefs'] }),
    );
  });

  it('prefetches business profile query', () => {
    prefetchDashboardData();

    expect(queryClient.prefetchQuery).toHaveBeenCalledWith(
      expect.objectContaining({ queryKey: ['profile'] }),
    );
  });

  it('prefetches template list query', () => {
    prefetchDashboardData();

    expect(queryClient.prefetchQuery).toHaveBeenCalledWith(
      expect.objectContaining({ queryKey: ['templates'] }),
    );
  });

  it('does NOT prefetch online menus (Erevna is the Questioner product)', () => {
    prefetchDashboardData();

    expect(queryClient.prefetchQuery).not.toHaveBeenCalledWith(
      expect.objectContaining({ queryKey: ['menus'] }),
    );
  });

  it('does not throw when prefetchQuery rejects', () => {
    (queryClient.prefetchQuery as jest.Mock).mockRejectedValue(new Error('fail'));

    expect(() => prefetchDashboardData()).not.toThrow();
  });
});
