import React from 'react';

import {
  bytesToMb,
  DEFAULT_ALLOWED_CONTENT_TYPES,
  mbToBytes,
  toggleContentType,
} from '@/components/DynamicForm/questionTypes/fileUploadHelpers';
import Checkbox from '@/components/Shared/Checkbox';
import FieldLabel from '@/components/Shared/FieldLabel';
import { FM } from '@/localization/helpers';
import type { QuestionConfig } from '@/server/autoGeneratedHooks/questioner/models';
import { isValueDefined } from '@/utils/is';

import NumberField from './NumberField';

interface Props {
  config: QuestionConfig | null | undefined;
  onChange: (config: QuestionConfig) => void;
}

interface ContentTypePreset {
  value: string;
  labelKey: string;
}

const CONTENT_TYPE_PRESETS: readonly ContentTypePreset[] = [
  { value: 'image/jpeg', labelKey: 'quizTemplates.fileUpload.type.jpeg' },
  { value: 'image/png', labelKey: 'quizTemplates.fileUpload.type.png' },
  { value: 'image/gif', labelKey: 'quizTemplates.fileUpload.type.gif' },
  { value: 'image/webp', labelKey: 'quizTemplates.fileUpload.type.webp' },
  { value: 'application/pdf', labelKey: 'quizTemplates.fileUpload.type.pdf' },
];

/** Per-type config editor for the file-upload question (allowed types, size, count). */
const FileUploadConfigEditor = ({ config, onChange }: Props): React.ReactElement => {
  const current = config ?? {};
  const selectedTypes = isValueDefined(current.allowedContentTypes)
    ? current.allowedContentTypes
    : [...DEFAULT_ALLOWED_CONTENT_TYPES];

  function setField<K extends keyof QuestionConfig>(key: K, value: QuestionConfig[K]): void {
    onChange({ ...current, [key]: value });
  }

  const maxSizeMb = isValueDefined(current.maxSizeBytes) ? bytesToMb(current.maxSizeBytes) : undefined;

  return (
    <>
      <FieldLabel text={FM('quizTemplates.fileUpload.allowedTypes')} />
      {CONTENT_TYPE_PRESETS.map((preset) => (
        <Checkbox
          key={preset.value}
          isChecked={selectedTypes.includes(preset.value)}
          label={FM(preset.labelKey)}
          testID={`file-upload-type-${preset.value}`}
          onPress={() => setField('allowedContentTypes', toggleContentType(selectedTypes, preset.value))}
        />
      ))}

      <NumberField
        accessibilityHint={FM('quizTemplates.fileUpload.maxSizeHint')}
        accessibilityLabel={FM('quizTemplates.fileUpload.maxSizeLabel')}
        label={FM('quizTemplates.fileUpload.maxSize')}
        testID="file-upload-max-size-input"
        value={maxSizeMb}
        onChange={(mb) => setField('maxSizeBytes', isValueDefined(mb) ? mbToBytes(mb) : null)}
      />

      <NumberField
        accessibilityHint={FM('quizTemplates.fileUpload.maxFilesHint')}
        accessibilityLabel={FM('quizTemplates.fileUpload.maxFilesLabel')}
        label={FM('quizTemplates.fileUpload.maxFiles')}
        testID="file-upload-max-files-input"
        value={current.maxFiles ?? undefined}
        onChange={(count) => setField('maxFiles', count ?? null)}
      />
    </>
  );
};

export default FileUploadConfigEditor;
