import React, { useCallback, useMemo } from 'react';

import { StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

import {
  getMatrixColumns,
  getMatrixRows,
  toColValue,
  toRowValue,
  type MatrixAxisItem,
} from '@/components/DynamicForm/questionTypes/matrixEncoding';
import { FM } from '@/localization/helpers';
import type { Option } from '@/server/autoGeneratedHooks/questioner/models';
import { TestIds } from '@/shared/testIds';
import { useTheme } from '@/theme/hooks/useTheme';

interface Props {
  options: Option[];
  onChange: (opts: Option[]) => void;
}

const INPUT_PADDING = 6;
const ROW_MARGIN = 6;

const styles = StyleSheet.create({
  axisBlock: { marginBottom: 12 },
  itemRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: ROW_MARGIN },
  input: { flex: 1, padding: INPUT_PADDING },
});

/** Generate a stable-ish id for a new axis item. */
function nextId(prefix: string, existing: MatrixAxisItem[]): string {
  const max = existing.reduce((acc, item) => {
    const numeric = Number(item.id.replace(/\D/g, ''));
    return Number.isNaN(numeric) ? acc : Math.max(acc, numeric);
  }, 0);
  return `${prefix}${max + 1}`;
}

/**
 * Matrix builder editor: edits the ROW and COLUMN axes, persisting both into the
 * shared `options` array using the `row:` / `col:` value-prefix convention so the
 * matrix needs no backend Answer/Config change.
 */
const MatrixEditor = ({ options, onChange }: Props): React.ReactElement => {
  const { theme } = useTheme();
  const primary = theme.palette.primary['500'];
  const errorColor = theme.semantic.error['500'];

  const rows = useMemo(() => getMatrixRows(options), [options]);
  const columns = useMemo(() => getMatrixColumns(options), [options]);

  const rebuild = useCallback(
    (nextRows: MatrixAxisItem[], nextColumns: MatrixAxisItem[]) => {
      const rowOptions: Option[] = nextRows.map((row) => ({ label: row.label, value: toRowValue(row.id) }));
      const colOptions: Option[] = nextColumns.map((col) => ({ label: col.label, value: toColValue(col.id) }));
      onChange([...rowOptions, ...colOptions]);
    },
    [onChange],
  );

  const setRowLabel = (idx: number, label: string): void => {
    const next = rows.map((row, i) => (i === idx ? { ...row, label } : row));
    rebuild(next, columns);
  };
  const setColLabel = (idx: number, label: string): void => {
    const next = columns.map((col, i) => (i === idx ? { ...col, label } : col));
    rebuild(rows, next);
  };
  const addRow = (): void => rebuild([...rows, { id: nextId('r', rows), label: FM('quizTemplates.matrixRow') }], columns);
  const addColumn = (): void => rebuild(rows, [...columns, { id: nextId('c', columns), label: FM('quizTemplates.matrixColumn') }]);
  const removeRow = (idx: number): void => rebuild(rows.filter((_row, i) => i !== idx), columns);
  const removeColumn = (idx: number): void => rebuild(rows, columns.filter((_col, i) => i !== idx));

  const removeStyle = useMemo(() => ({ color: errorColor }), [errorColor]);
  const addStyle = useMemo(() => ({ color: primary }), [primary]);

  return (
    <View>
      <Text>{FM('quizTemplates.matrixRows')}</Text>
      <View style={styles.axisBlock}>
        {rows.map((row, i) => (
          <View key={row.id} style={styles.itemRow}>
            <TextInput
              accessibilityHint={FM('quizTemplates.matrixRowInputHint')}
              accessibilityLabel={FM('quizTemplates.matrixRowInputLabel')}
              placeholder={FM('quizTemplates.matrixRow')}
              style={styles.input}
              testID={`${TestIds.MATRIX_EDITOR_ROW_INPUT}-${row.id}`}
              value={row.label}
              onChangeText={(v) => setRowLabel(i, v)}
            />
            <TouchableOpacity
              accessibilityHint={FM('quizTemplates.matrixRemoveRowHint')}
              accessibilityLabel={FM('quizTemplates.matrixRemoveRow')}
              accessibilityRole="button"
              testID={`${TestIds.MATRIX_EDITOR_REMOVE_ROW}-${row.id}`}
              onPress={() => removeRow(i)}
            >
              <Text style={removeStyle}>{FM('quizTemplates.matrixRemoveRow')}</Text>
            </TouchableOpacity>
          </View>
        ))}
        <TouchableOpacity
          accessibilityHint={FM('quizTemplates.matrixAddRowHint')}
          accessibilityLabel={FM('quizTemplates.matrixAddRow')}
          accessibilityRole="button"
          testID={TestIds.MATRIX_EDITOR_ADD_ROW}
          onPress={addRow}
        >
          <Text style={addStyle}>{FM('quizTemplates.matrixAddRow')}</Text>
        </TouchableOpacity>
      </View>

      <Text>{FM('quizTemplates.matrixColumns')}</Text>
      <View style={styles.axisBlock}>
        {columns.map((col, i) => (
          <View key={col.id} style={styles.itemRow}>
            <TextInput
              accessibilityHint={FM('quizTemplates.matrixColumnInputHint')}
              accessibilityLabel={FM('quizTemplates.matrixColumnInputLabel')}
              placeholder={FM('quizTemplates.matrixColumn')}
              style={styles.input}
              testID={`${TestIds.MATRIX_EDITOR_COLUMN_INPUT}-${col.id}`}
              value={col.label}
              onChangeText={(v) => setColLabel(i, v)}
            />
            <TouchableOpacity
              accessibilityHint={FM('quizTemplates.matrixRemoveColumnHint')}
              accessibilityLabel={FM('quizTemplates.matrixRemoveColumn')}
              accessibilityRole="button"
              testID={`${TestIds.MATRIX_EDITOR_REMOVE_COLUMN}-${col.id}`}
              onPress={() => removeColumn(i)}
            >
              <Text style={removeStyle}>{FM('quizTemplates.matrixRemoveColumn')}</Text>
            </TouchableOpacity>
          </View>
        ))}
        <TouchableOpacity
          accessibilityHint={FM('quizTemplates.matrixAddColumnHint')}
          accessibilityLabel={FM('quizTemplates.matrixAddColumn')}
          accessibilityRole="button"
          testID={TestIds.MATRIX_EDITOR_ADD_COLUMN}
          onPress={addColumn}
        >
          <Text style={addStyle}>{FM('quizTemplates.matrixAddColumn')}</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};

export default MatrixEditor;
