import React from 'react';

import FieldLabel from '@/components/Shared/FieldLabel';
import { FM } from '@/localization/helpers';
import type { QuestionConfig } from '@/server/autoGeneratedHooks/questioner/models';

import NumberField from './NumberField';
import TextFieldRow from './TextFieldRow';

interface Props {
  config: QuestionConfig | null | undefined;
  /** When true, scale bounds are fixed (NPS); only endpoint labels are editable. */
  fixedBounds?: boolean;
  onChange: (config: QuestionConfig) => void;
}

/** Per-type config editor for scale-based questions (Rating, LinearScale, NPS labels). */
const ScaleConfigEditor = ({ config, fixedBounds, onChange }: Props): React.ReactElement => {
  const current = config ?? {};

  function setField<K extends keyof QuestionConfig>(key: K, value: QuestionConfig[K]): void {
    onChange({ ...current, [key]: value });
  }

  return (
    <>
      <FieldLabel text={FM('quizTemplates.scaleConfig')} />
      {fixedBounds !== true ? (
        <>
          <NumberField
            accessibilityHint={FM('quizTemplates.scaleMinInputHint')}
            accessibilityLabel={FM('quizTemplates.scaleMinInputLabel')}
            label={FM('quizTemplates.scaleMin')}
            testID="scale-min-input"
            value={current.scaleMin ?? undefined}
            onChange={(v) => setField('scaleMin', v ?? null)}
          />
          <NumberField
            accessibilityHint={FM('quizTemplates.scaleMaxInputHint')}
            accessibilityLabel={FM('quizTemplates.scaleMaxInputLabel')}
            label={FM('quizTemplates.scaleMax')}
            testID="scale-max-input"
            value={current.scaleMax ?? undefined}
            onChange={(v) => setField('scaleMax', v ?? null)}
          />
          <NumberField
            accessibilityHint={FM('quizTemplates.scaleStepInputHint')}
            accessibilityLabel={FM('quizTemplates.scaleStepInputLabel')}
            label={FM('quizTemplates.scaleStep')}
            testID="scale-step-input"
            value={current.scaleStep ?? undefined}
            onChange={(v) => setField('scaleStep', v ?? null)}
          />
        </>
      ) : null}
      <TextFieldRow
        accessibilityHint={FM('quizTemplates.minLabelInputHint')}
        accessibilityLabel={FM('quizTemplates.minLabelInputLabel')}
        label={FM('quizTemplates.minLabel')}
        testID="scale-min-label-input"
        value={current.minLabel ?? ''}
        onChange={(v) => setField('minLabel', v)}
      />
      <TextFieldRow
        accessibilityHint={FM('quizTemplates.maxLabelInputHint')}
        accessibilityLabel={FM('quizTemplates.maxLabelInputLabel')}
        label={FM('quizTemplates.maxLabel')}
        testID="scale-max-label-input"
        value={current.maxLabel ?? ''}
        onChange={(v) => setField('maxLabel', v)}
      />
    </>
  );
};

export default ScaleConfigEditor;
