import React from 'react';

import FieldLabel from '@/components/Shared/FieldLabel';
import { FM } from '@/localization/helpers';
import type { ValidationRules } from '@/server/autoGeneratedHooks/questioner/models';

import NumberField from './NumberField';
import TextFieldRow from './TextFieldRow';
import { RuleShape, ruleShapeForType } from './validationRuleShape';

interface Props {
  questionType: number | undefined;
  rules: ValidationRules | null | undefined;
  onChange: (rules: ValidationRules) => void;
}

type SetField = <K extends keyof ValidationRules>(key: K, value: ValidationRules[K]) => void;

const TextRules = ({ rules, setField }: { rules: ValidationRules; setField: SetField }): React.ReactElement => {
  return (
    <>
      <NumberField
        accessibilityHint={FM('quizTemplates.ruleMinLengthInputHint')}
        accessibilityLabel={FM('quizTemplates.ruleMinLengthInputLabel')}
        label={FM('quizTemplates.ruleMinLength')}
        testID="rule-min-length-input"
        value={rules.minLength ?? undefined}
        onChange={(v) => setField('minLength', v ?? null)}
      />
      <NumberField
        accessibilityHint={FM('quizTemplates.ruleMaxLengthInputHint')}
        accessibilityLabel={FM('quizTemplates.ruleMaxLengthInputLabel')}
        label={FM('quizTemplates.ruleMaxLength')}
        testID="rule-max-length-input"
        value={rules.maxLength ?? undefined}
        onChange={(v) => setField('maxLength', v ?? null)}
      />
      <TextFieldRow
        accessibilityHint={FM('quizTemplates.rulePatternInputHint')}
        accessibilityLabel={FM('quizTemplates.rulePatternInputLabel')}
        label={FM('quizTemplates.rulePattern')}
        testID="rule-pattern-input"
        value={rules.pattern ?? ''}
        onChange={(v) => setField('pattern', v)}
      />
      <TextFieldRow
        accessibilityHint={FM('quizTemplates.rulePatternMessageInputHint')}
        accessibilityLabel={FM('quizTemplates.rulePatternMessageInputLabel')}
        label={FM('quizTemplates.rulePatternMessage')}
        testID="rule-pattern-message-input"
        value={rules.patternMessage ?? ''}
        onChange={(v) => setField('patternMessage', v)}
      />
    </>
  );
}

const NumericRules = ({ rules, setField }: { rules: ValidationRules; setField: SetField }): React.ReactElement => {
  return (
    <>
      <NumberField
        accessibilityHint={FM('quizTemplates.ruleMinInputHint')}
        accessibilityLabel={FM('quizTemplates.ruleMinInputLabel')}
        label={FM('quizTemplates.ruleMin')}
        testID="rule-min-input"
        value={rules.min ?? undefined}
        onChange={(v) => setField('min', v ?? null)}
      />
      <NumberField
        accessibilityHint={FM('quizTemplates.ruleMaxInputHint')}
        accessibilityLabel={FM('quizTemplates.ruleMaxInputLabel')}
        label={FM('quizTemplates.ruleMax')}
        testID="rule-max-input"
        value={rules.max ?? undefined}
        onChange={(v) => setField('max', v ?? null)}
      />
    </>
  );
}

const MultiRules = ({ rules, setField }: { rules: ValidationRules; setField: SetField }): React.ReactElement => {
  return (
    <>
      <NumberField
        accessibilityHint={FM('quizTemplates.ruleMinSelectionsInputHint')}
        accessibilityLabel={FM('quizTemplates.ruleMinSelectionsInputLabel')}
        label={FM('quizTemplates.ruleMinSelections')}
        testID="rule-min-selections-input"
        value={rules.minSelections ?? undefined}
        onChange={(v) => setField('minSelections', v ?? null)}
      />
      <NumberField
        accessibilityHint={FM('quizTemplates.ruleMaxSelectionsInputHint')}
        accessibilityLabel={FM('quizTemplates.ruleMaxSelectionsInputLabel')}
        label={FM('quizTemplates.ruleMaxSelections')}
        testID="rule-max-selections-input"
        value={rules.maxSelections ?? undefined}
        onChange={(v) => setField('maxSelections', v ?? null)}
      />
    </>
  );
}

/** Per-type validation-rules editor (length/pattern, min/max, or selection counts). */
const ValidationRulesEditor = ({ questionType, rules, onChange }: Props): React.ReactElement | null => {
  const current = rules ?? {};
  const shape = ruleShapeForType(questionType);

  const setField: SetField = (key, value) => onChange({ ...current, [key]: value });

  if (shape === RuleShape.None) return null;

  return (
    <>
      <FieldLabel text={FM('quizTemplates.validationRules')} />
      {shape === RuleShape.Text ? <TextRules rules={current} setField={setField} /> : null}
      {shape === RuleShape.Numeric ? <NumericRules rules={current} setField={setField} /> : null}
      {shape === RuleShape.Multi ? <MultiRules rules={current} setField={setField} /> : null}
    </>
  );
};

export default ValidationRulesEditor;
