import { QuestionType } from '@/server/autoGeneratedHooks/questioner/models/questionType';
import { isValueDefined } from '@/utils/is';

const NUMERIC_TYPES: ReadonlySet<number> = new Set<number>([
  QuestionType.Number,
  QuestionType.Rating,
  QuestionType.Nps,
  QuestionType.LinearScale,
]);

const MULTI_TYPES: ReadonlySet<number> = new Set<number>([
  QuestionType.Checkbox,
  QuestionType.MultipleChoice,
]);

/** Which validation-rule group applies to a question type. */
export const enum RuleShape {
  Text = 'text',
  Numeric = 'numeric',
  Multi = 'multi',
  None = 'none',
}

/** Resolve the validation-rule group for a given API question type. */
export function ruleShapeForType(type: number | undefined): RuleShape {
  if (!isValueDefined(type)) return RuleShape.Text;
  if (type === QuestionType.Text) return RuleShape.Text;
  if (NUMERIC_TYPES.has(type)) return RuleShape.Numeric;
  if (MULTI_TYPES.has(type)) return RuleShape.Multi;
  return RuleShape.None;
}
