/**
 * Tests for the question-type registry lookups and per-type validation wiring.
 */
import {
  getAllEntries,
  getEntryByApiType,
  getEntryByUiType,
  uiTypeSupportsOptions,
  NUMERIC_API_TYPES,
  SCALE_API_TYPES,
  FIXED_SCALE_API_TYPES,
} from './registry';
import { type ValidationMessages } from './validation';
import { QuestionType as ApiQuestionType } from '../../../server/autoGeneratedHooks/questioner/models/questionType';
import QuestionType from '../../../shared/enums/QuestionType';

import type { Question } from '../interfaces';

const MESSAGES: ValidationMessages = {
  required: 'required', minLength: 'minLength {{p1}}', maxLength: 'maxLength {{p1}}',
  pattern: 'pattern', min: 'min {{p1}}', max: 'max {{p1}}',
  minSelections: 'minSel {{p1}}', maxSelections: 'maxSel {{p1}}',
};

describe('registry - lookups', () => {
  it('maps each UI type to the matching API numeric type', () => {
    expect(getEntryByUiType(QuestionType.Rating).apiType).toBe(ApiQuestionType.Rating);
    expect(getEntryByUiType(QuestionType.LinearScale).apiType).toBe(ApiQuestionType.LinearScale);
  });

  it('maps each API type back to its UI type', () => {
    expect(getEntryByApiType(ApiQuestionType.Number).uiType).toBe(QuestionType.Number);
    expect(getEntryByApiType(ApiQuestionType.Date).uiType).toBe(QuestionType.Date);
  });

  it('defaults unknown lookups to Text', () => {
    expect(getEntryByApiType(999).uiType).toBe(QuestionType.Text);
    expect(getEntryByApiType(undefined).uiType).toBe(QuestionType.Text);
  });

  it('registers all 10 types', () => {
    expect(getAllEntries()).toHaveLength(10);
  });

  it('reports option support correctly', () => {
    expect(uiTypeSupportsOptions(QuestionType.Radio)).toBe(true);
    expect(uiTypeSupportsOptions(QuestionType.Rating)).toBe(false);
    expect(uiTypeSupportsOptions(QuestionType.Number)).toBe(false);
  });
});

describe('registry - classification sets', () => {
  it('treats Rating/Nps/Number/LinearScale as numeric', () => {
    [ApiQuestionType.Rating, ApiQuestionType.Nps, ApiQuestionType.Number, ApiQuestionType.LinearScale]
      .forEach((t) => expect(NUMERIC_API_TYPES.has(t)).toBe(true));
    expect(NUMERIC_API_TYPES.has(ApiQuestionType.Text)).toBe(false);
  });

  it('treats Rating/Nps/LinearScale as scale types', () => {
    expect(SCALE_API_TYPES.has(ApiQuestionType.Rating)).toBe(true);
    expect(SCALE_API_TYPES.has(ApiQuestionType.Number)).toBe(false);
  });

  it('treats only Nps as fixed-bounds scale', () => {
    expect(FIXED_SCALE_API_TYPES.has(ApiQuestionType.Nps)).toBe(true);
    expect(FIXED_SCALE_API_TYPES.has(ApiQuestionType.Rating)).toBe(false);
  });
});

describe('registry - validate', () => {
  function numberQuestion(rules: Question['validationRules'], required = false): Question {
    return { id: 'q', name: 'N', type: QuestionType.Number, page: 1, order: 1, isRequired: required, validationRules: rules };
  }

  it('enforces required before rule checks', () => {
    const entry = getEntryByUiType(QuestionType.Number);
    expect(entry.validate?.(undefined, numberQuestion({ min: 1 }, true), MESSAGES)).toBe('required');
  });

  it('applies numeric min rule via the registry validator', () => {
    const entry = getEntryByUiType(QuestionType.Rating);
    const q: Question = { id: 'r', name: 'R', type: QuestionType.Rating, page: 1, order: 1, validationRules: { min: 3 } };
    expect(entry.validate?.(1, q, MESSAGES)).toBe('min 3');
  });

  it('returns undefined for a valid optional answer', () => {
    const entry = getEntryByUiType(QuestionType.Number);
    expect(entry.validate?.(5, numberQuestion({ min: 1, max: 10 }), MESSAGES)).toBeUndefined();
  });
});
