/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */

import type { FileReference } from './fileReference';

export interface Answer {
  /** @nullable */
  boolValue?: boolean | null;
  /** @nullable */
  stringValue?: string | null;
  /** @nullable */
  numericValue?: number | null;
  /** @nullable */
  multiValues?: string[] | null;
  /** File-upload answer: references to uploaded files (not the bytes). @nullable */
  files?: FileReference[] | null;
}
