/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */
// Hand-extended to match the backend file-upload contract (question type 12).
// A real Orval regen against the deployed API will reproduce this file identically.

/** A stored-file reference returned by the public upload endpoint (not the bytes). */
export interface FileReference {
  objectKey: string;
  fileName: string;
  contentType: string;
  sizeBytes: number;
}
