/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */

export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionType = {
  Text: 0,
  MultipleChoice: 1,
  Checkbox: 2,
  Radio: 3,
  Dropdown: 4,
  // Hand-extended to match the backend contract (5 new types). A real Orval regen
  // against the deployed API will reproduce these identically.
  Rating: 5,
  Nps: 6,
  Number: 7,
  Date: 8,
  LinearScale: 9,
} as const;
