/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */
// Hand-extended to match the backend contract. A real Orval regen against the
// deployed API will reproduce this file identically.

export interface QuestionConfig {
  /** @nullable */
  scaleMin?: number | null;
  /** @nullable */
  scaleMax?: number | null;
  /** @nullable */
  scaleStep?: number | null;
  /** @nullable */
  minLabel?: string | null;
  /** @nullable */
  maxLabel?: string | null;
}
