/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionerContents } from './questionerContents';

export type QuestionerTemplateDtoAllOf = {
  name?: string;
  /** @nullable */
  description?: string | null;
  contents?: QuestionerContents;
  contentsJson?: string;
  isActive?: boolean;
  /** @nullable Soft-closing date (UTC ISO); null = no closing date. */
  closingDate?: string | null;
  /** @nullable Response quota; null = unlimited. */
  maxResponses?: number | null;
  /** Respondent identity collection mode: 0=Anonymous, 1=Optional, 2=Required. */
  respondentContactMode?: number;
};
