/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */
// Hand-extended to match the backend contract. A real Orval regen against the
// deployed API will reproduce this file identically.

export interface ValidationRules {
  /** @nullable */
  minLength?: number | null;
  /** @nullable */
  maxLength?: number | null;
  /** @nullable */
  pattern?: string | null;
  /** @nullable */
  patternMessage?: string | null;
  /** @nullable */
  min?: number | null;
  /** @nullable */
  max?: number | null;
  /** @nullable */
  minSelections?: number | null;
  /** @nullable */
  maxSelections?: number | null;
}
