import { useMutation, useQueryClient } from '@tanstack/react-query';

import { getOnlineMenuWebMenuListQueryKey, getOnlineMenuWebMenuGetByIdQueryKey } from '../server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';
import { customInstance } from '../server/httpClient';

import type { UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

export async function activateMenu(externalId: string): Promise<unknown> {
  return customInstance({
    url: `/api/v1/TenantMenus/${externalId}/activate`,
    method: 'PATCH',
  });
}

export async function deactivateMenu(externalId: string): Promise<unknown> {
  return customInstance({
    url: `/api/v1/TenantMenus/${externalId}/deactivate`,
    method: 'PATCH',
  });
}

export function useActivateMenu<TError = unknown, TContext = unknown>(
  options?: UseMutationOptions<
    unknown,
    TError,
    { externalId: string },
    TContext
  >
): UseMutationResult<unknown, TError, { externalId: string }, TContext> {
  const queryClient = useQueryClient();
  const { onSuccess: _onSuccess, ...restOptions } = options ?? {};

  return useMutation({
    ...restOptions,
    mutationFn: async ({ externalId }) => activateMenu(externalId),
    onSuccess: (data, variables, onMutateResult, context) => {
      queryClient.invalidateQueries({
        queryKey: getOnlineMenuWebMenuListQueryKey(),
      }).catch(() => {
      });
      queryClient.invalidateQueries({
        queryKey: getOnlineMenuWebMenuGetByIdQueryKey(variables.externalId),
      }).catch(() => {
      });

      if (options?.onSuccess)
        options.onSuccess(data, variables, onMutateResult, context);

    },
  });
}

export function useDeactivateMenu<TError = unknown, TContext = unknown>(
  options?: UseMutationOptions<
    unknown,
    TError,
    { externalId: string },
    TContext
  >
): UseMutationResult<unknown, TError, { externalId: string }, TContext> {
  const queryClient = useQueryClient();
  const { onSuccess: _onSuccess, ...restOptions } = options ?? {};

  return useMutation({
    ...restOptions,
    mutationFn: async ({ externalId }) => deactivateMenu(externalId),
    onSuccess: (data, variables, onMutateResult, context) => {
      queryClient.invalidateQueries({
        queryKey: getOnlineMenuWebMenuListQueryKey(),
      }).catch(() => {
      });
      queryClient.invalidateQueries({
        queryKey: getOnlineMenuWebMenuGetByIdQueryKey(variables.externalId),
      }).catch(() => {
      });

      if (options?.onSuccess)
        options.onSuccess(data, variables, onMutateResult, context);

    },
  });
}
