/**
 * Tests for useQuizTemplateEmbed hook.
 * Focuses on state management logic for the survey embed widget modal.
 */
import { renderHook, act } from '@testing-library/react-native';

import { useQuizTemplateEmbed } from './useQuizTemplateEmbed';

import type { QuestionerTemplateDto } from '../server/autoGeneratedHooks/questioner/models/questionerTemplateDto';

jest.mock('react-native', () => ({
  Platform: { OS: 'web' },
}));

const mockOrigin = 'https://erevna.test';

Object.defineProperty(window, 'location', {
  value: { origin: mockOrigin },
  writable: true,
});

describe('useQuizTemplateEmbed', () => {
  const mockItems: QuestionerTemplateDto[] = [
    { externalId: 'survey-1', name: 'Customer NPS' },
    { externalId: 'survey-2', name: 'Onboarding Feedback' },
  ];

  it('initializes with null state and not visible', () => {
    const { result } = renderHook(() => useQuizTemplateEmbed(mockItems));
    expect(result.current.embedState).toBeNull();
    expect(result.current.isEmbedVisible).toBe(false);
  });

  it('sets embedState with the origin as publicUrl for a valid id', () => {
    const { result } = renderHook(() => useQuizTemplateEmbed(mockItems));

    act(() => {
      result.current.handleEmbed('survey-1');
    });

    expect(result.current.embedState).toEqual({
      surveyName: 'Customer NPS',
      publicUrl: mockOrigin,
      surveyId: 'survey-1',
    });
    expect(result.current.isEmbedVisible).toBe(true);
  });

  it('does not set state for a non-existent id', () => {
    const { result } = renderHook(() => useQuizTemplateEmbed(mockItems));

    act(() => {
      result.current.handleEmbed('missing');
    });

    expect(result.current.embedState).toBeNull();
    expect(result.current.isEmbedVisible).toBe(false);
  });

  it('clears state on close', () => {
    const { result } = renderHook(() => useQuizTemplateEmbed(mockItems));

    act(() => {
      result.current.handleEmbed('survey-2');
    });
    expect(result.current.isEmbedVisible).toBe(true);

    act(() => {
      result.current.handleCloseEmbed();
    });
    expect(result.current.embedState).toBeNull();
    expect(result.current.isEmbedVisible).toBe(false);
  });
});
