import { useCallback, useState } from 'react';

import { buildPublicSurveyUrl } from '../components/OnlineMenus/QrCode';
import { isValueDefined } from '../utils/is';

import type { QuestionerTemplateDto } from '../server/autoGeneratedHooks/questioner/models/questionerTemplateDto';

interface QrCodeState {
  surveyName: string;
  publicUrl: string;
}

interface UseQuizTemplateQrCodeResult {
  qrCodeState: QrCodeState | null;
  isQrCodeVisible: boolean;
  handleQrCode: (externalId: string) => void;
  handleCloseQrCode: () => void;
}

/**
 * Manages the Share/QR modal state for survey (questioner) templates.
 * Mirrors {@link useMenuQrCode}; builds the public survey URL for the
 * selected template.
 */
export function useQuizTemplateQrCode(items: QuestionerTemplateDto[]): UseQuizTemplateQrCodeResult {
  const [qrCodeState, setQrCodeState] = useState<QrCodeState | null>(null);

  const handleQrCode = useCallback(
    (externalId: string) => {
      const item = items.find((t) => t.externalId === externalId);
      if (isValueDefined(item))
        setQrCodeState({
          surveyName: item.name ?? '',
          publicUrl: buildPublicSurveyUrl(externalId),
        });
    },
    [items],
  );

  const handleCloseQrCode = useCallback(() => {
    setQrCodeState(null);
  }, []);

  return {
    qrCodeState,
    isQrCodeVisible: isValueDefined(qrCodeState),
    handleQrCode,
    handleCloseQrCode,
  };
}
