import { useCallback, useState } from 'react';

import { Platform } from 'react-native';

import { isValueDefined } from '../utils/is';

import type { QuestionerTemplateDto } from '../server/autoGeneratedHooks/questioner/models/questionerTemplateDto';

interface EmbedState {
  surveyName: string;
  publicUrl: string;
  surveyId: string;
}

interface UseQuizTemplateEmbedResult {
  embedState: EmbedState | null;
  isEmbedVisible: boolean;
  handleEmbed: (externalId: string) => void;
  handleCloseEmbed: () => void;
}

/** The app origin used as the embed `publicUrl` (the embed builder appends the route). */
function buildPublicOrigin(): string {
  if (Platform.OS === 'web' && typeof window !== 'undefined') return window.location.origin;
  return '';
}

/**
 * Manages the Embed-widget modal state for survey (questioner) templates.
 * Mirrors {@link useMenuEmbed}; the embed builder appends `/public/survey/embed/{id}`.
 */
export function useQuizTemplateEmbed(items: QuestionerTemplateDto[]): UseQuizTemplateEmbedResult {
  const [embedState, setEmbedState] = useState<EmbedState | null>(null);

  const handleEmbed = useCallback(
    (externalId: string) => {
      const item = items.find((t) => t.externalId === externalId);
      if (isValueDefined(item))
        setEmbedState({
          surveyName: item.name ?? '',
          publicUrl: buildPublicOrigin(),
          surveyId: externalId,
        });
    },
    [items],
  );

  const handleCloseEmbed = useCallback(() => {
    setEmbedState(null);
  }, []);

  return {
    embedState,
    isEmbedVisible: isValueDefined(embedState),
    handleEmbed,
    handleCloseEmbed,
  };
}
