/**
 * useSurveyDraftSave - owns the "save & continue later" action for the public
 * survey: persists the current answers and exposes the shareable resume URL.
 */
import { useCallback, useMemo, useState } from 'react';

import { Platform } from 'react-native';

import { useSaveDraft } from '../server/customHooks/useSaveDraft';

import type { QuestionerContents } from '../server/autoGeneratedHooks/questioner/models';

const DRAFT_QUERY_PARAM = 'draft';

/** Builds a resume link for the current public-survey page with the token attached. */
function buildResumeUrl(token: string): string {
  const unavailable = token === '' || Platform.OS !== 'web' || typeof window === 'undefined';
  if (unavailable) return '';
  const { origin, pathname } = window.location;
  return `${origin}${pathname}?${DRAFT_QUERY_PARAM}=${token}`;
}

export interface SurveyDraftSave {
  save: (contents: QuestionerContents, respondentEmail?: string) => Promise<void>;
  isSaving: boolean;
  savedToken: string;
  resumeUrl: string;
}

export function useSurveyDraftSave(externalId: string, existingToken: string): SurveyDraftSave {
  const { mutateAsync, isPending } = useSaveDraft(externalId);
  const [savedToken, setSavedToken] = useState(existingToken);

  const save = useCallback(
    async (contents: QuestionerContents, respondentEmail?: string): Promise<void> => {
      const result = await mutateAsync({
        contents,
        draftToken: savedToken === '' ? undefined : savedToken,
        respondentEmail,
      });
      setSavedToken(result.token);
    },
    [mutateAsync, savedToken],
  );

  const resumeUrl = useMemo(() => buildResumeUrl(savedToken), [savedToken]);

  return { save, isSaving: isPending, savedToken, resumeUrl };
}
