import { useMemo } from 'react';

import type { DashboardData } from '@/components/Dashboard/types';
import { useQuestionerWebQuestionerTemplatesList } from '@/server/autoGeneratedHooks/questioner/questionertemplates/questionertemplates';

/**
 * Erevna is the Questioner product. The dashboard never reads
 * online-menu data -- calling the menu list hook here would
 * (a) make a wasted network call to onlinemenu-api.dloizides.com, and
 * (b) leak through the cross-realm wall (the menu API rejects
 * questioner-realm tokens with 401, polluting error monitoring).
 *
 * The menu query was removed as part of the Phase-3 product
 * feature-strip. The DashboardData shape is shared with Katalogos, so
 * `menuCount` / `hasMenus` remain in the returned object but are
 * hard-coded to zero/false.
 */
export function useDashboardData(): DashboardData {
  const templateQuery = useQuestionerWebQuestionerTemplatesList();

  return useMemo((): DashboardData => {
    const templates = templateQuery.data?.questionerTemplates;
    const templateCount = Array.isArray(templates) ? templates.length : 0;
    const hasTemplates = templateCount > 0;

    return {
      menuCount: 0,
      templateCount,
      isLoading: templateQuery.isLoading,
      hasMenus: false,
      hasTemplates,
      isEmpty: !hasTemplates,
    };
  }, [templateQuery.data, templateQuery.isLoading]);
}
