import { useMemo } from 'react';

import type { DashboardData } from '@/components/Dashboard/types';
import { useQuestionerWebQuestionerTemplatesList } from '@/server/autoGeneratedHooks/questioner/questionertemplates/questionertemplates';

export function useDashboardData(): DashboardData {
  const templateQuery = useQuestionerWebQuestionerTemplatesList();

  return useMemo((): DashboardData => {
    const templates = templateQuery.data?.questionerTemplates;
    const templateCount = Array.isArray(templates) ? templates.length : 0;
    const hasTemplates = templateCount > 0;

    return {
      menuCount: 0,
      templateCount,
      isLoading: templateQuery.isLoading,
      hasMenus: false,
      hasTemplates,
      isEmpty: !hasTemplates,
    };
  }, [templateQuery.data, templateQuery.isLoading]);
}
