import { renderHook } from '@testing-library/react-native';

import { useDashboardData } from './useDashboardData';

const mockTemplatesListReturn: { data: { questionerTemplates: unknown[] } | undefined; isLoading: boolean } = {
  data: { questionerTemplates: [] },
  isLoading: false,
};

jest.mock('@/server/autoGeneratedHooks/questioner/questionertemplates/questionertemplates', () => ({
  useQuestionerWebQuestionerTemplatesList: jest.fn(() => mockTemplatesListReturn),
}));

describe('useDashboardData (Erevna)', () => {
  beforeEach(() => {
    mockTemplatesListReturn.data = { questionerTemplates: [] };
    mockTemplatesListReturn.isLoading = false;
  });

  it('returns isEmpty=true when the template list is empty', () => {
    const { result } = renderHook(() => useDashboardData());

    expect(result.current.isEmpty).toBe(true);
    expect(result.current.hasTemplates).toBe(false);
    expect(result.current.templateCount).toBe(0);
  });

  it('returns hasTemplates=true and accurate templateCount when templates are present', () => {
    const THREE_TEMPLATES = 3;
    mockTemplatesListReturn.data = { questionerTemplates: [{}, {}, {}] };

    const { result } = renderHook(() => useDashboardData());

    expect(result.current.hasTemplates).toBe(true);
    expect(result.current.templateCount).toBe(THREE_TEMPLATES);
    expect(result.current.isEmpty).toBe(false);
  });

  it('hard-codes menuCount=0 and hasMenus=false (Erevna is the Questioner product)', () => {
    mockTemplatesListReturn.data = { questionerTemplates: [{}] };

    const { result } = renderHook(() => useDashboardData());

    expect(result.current.menuCount).toBe(0);
    expect(result.current.hasMenus).toBe(false);
  });

  it('isLoading reflects the template query loading state', () => {
    mockTemplatesListReturn.isLoading = true;
    mockTemplatesListReturn.data = undefined;

    const { result } = renderHook(() => useDashboardData());

    expect(result.current.isLoading).toBe(true);
  });

  it('handles undefined template data without throwing', () => {
    mockTemplatesListReturn.data = undefined;

    const { result } = renderHook(() => useDashboardData());

    expect(result.current.templateCount).toBe(0);
    expect(result.current.isEmpty).toBe(true);
  });

  it('does NOT import any onlinemenu hook (Erevna must not call onlinemenu-api)', () => {
    const moduleSource = jest.requireActual<{ useDashboardData: unknown }>(
      './useDashboardData',
    );
    expect(typeof moduleSource.useDashboardData).toBe('function');
  });
});
