import type {
  GlobalTypography,
  ColorScheme,
  MenuLayoutSettings,
  HeaderSettings,
  SpacingSettings,
  MediaSettings,
  CategoryTypography,
  CategoryLayout,
  BoxStyling,
  ItemTypography,
  PriceStyle,
  ItemLayout,
  AvailabilityBadgeStyle,
  Badge,
} from './menuStyleTypes';
import type { NutritionalInfo } from './nutritionTypes';
import type {
  TenantMenusDto as GeneratedTenantMenusDto,
  Category as GeneratedCategory,
  MenuItem as GeneratedMenuItem,
} from '../server/autoGeneratedHooks/onlinemenu/models';
import type ScheduledDays from '../shared/enums/ScheduledDays';
import type TranslationStatus from '../shared/enums/TranslationStatus';

export type { NutritionalInfo } from './nutritionTypes';

export interface MenuSchedule {
  scheduledDays: ScheduledDays;
  startTime: string;
  endTime: string;
  isEnabled: boolean;
  timeZoneId: string;
}

let idCounter = 0;

export interface VariantGroup {
  /** Display name for this variant group (e.g., "Size", "Crust Type") */
  name: string;
  /** Sort order for displaying variant groups */
  displayOrder?: number;
  /** Whether the customer must select a variant from this group */
  isRequired?: boolean;
  /** Minimum number of variants the customer must select */
  minSelections?: number;
  /** Maximum number of variants the customer can select (null/undefined = unlimited) */
  maxSelections?: number | null;
  /** The variants available in this group */
  variants?: Variant[];
}

export interface Variant {
  /** Display name for this variant (e.g., "Small", "Medium", "Large") */
  name: string;
  /** Absolute price for this variant (replaces the item's base Price) */
  price: number;
  /** Sort order for displaying variants within the group */
  displayOrder?: number;
  /** Whether this variant is currently available */
  isAvailable?: boolean;
}

export interface ModifierGroup {
  /** Display name for this modifier group (e.g., "Extras", "Toppings") */
  name: string;
  /** Sort order for displaying modifier groups */
  displayOrder?: number;
  /** Whether the customer must select at least MinSelections modifiers */
  isRequired?: boolean;
  /** Minimum number of modifiers the customer must select */
  minSelections?: number;
  /** Maximum number of modifiers the customer can select (null/undefined = unlimited) */
  maxSelections?: number | null;
  /** The modifiers available in this group */
  modifiers?: Modifier[];
}

export interface Modifier {
  /** Display name for this modifier (e.g., "Add cheese", "Extra sauce") */
  name: string;
  /** Price adjustment for this modifier (added to the item/variant price) */
  priceAdjustment: number;
  /** Sort order for displaying modifiers within the group */
  displayOrder?: number;
  /** Whether this modifier is currently available */
  isAvailable?: boolean;
}


export interface TenantMenusDto extends GeneratedTenantMenusDto {
  isActive: boolean;

  schedule?: MenuSchedule | null;
}

export interface Category extends Omit<GeneratedCategory, 'items'> {
  id?: string;

  icon?: string | null;

  displayOrder?: number;

  imageContentId?: string | null;

  videoContentId?: string | null;

  items?: MenuItem[];

  imageSettings?: MediaSettings;

  videoSettings?: MediaSettings;

  typography?: CategoryTypography;

  layout?: CategoryLayout;

  styling?: BoxStyling;
}

export interface MenuItem extends GeneratedMenuItem {
  id?: string;

  displayOrder?: number;

  imageContentId?: string | null;

  videoContentId?: string | null;

  documentContentIds?: string[];

  imageSettings?: MediaSettings;

  videoSettings?: MediaSettings;

  typography?: ItemTypography;

  priceStyle?: PriceStyle;

  layout?: ItemLayout;

  styling?: BoxStyling;

  availabilityBadge?: AvailabilityBadgeStyle;

  badges?: Badge[];

  tags?: string[];

  isFeatured?: boolean;

  staffNote?: string | null;

  featuredOrder?: number;

  variantGroups?: VariantGroup[];

  modifierGroups?: ModifierGroup[];

  ingredients?: string | null;

  nutritionalInfo?: NutritionalInfo | null;

  detectedAllergens?: string[];

  availableFrom?: string | null;

  availableTo?: string | null;
}

export interface MenuContents {
  titleFont?: string | null;
  titleFontSize?: number;
  backgroundColor?: string | null;
  textColor?: string | null;
  categories?: Category[];

  schemaVersion?: number;

  typography?: GlobalTypography;

  colorScheme?: ColorScheme;

  layout?: MenuLayoutSettings;

  header?: HeaderSettings;

  spacing?: SpacingSettings;

  defaultMediaSettings?: MediaSettings;

  featuredSectionEnabled?: boolean;

  featuredSectionTitle?: string | null;
}

export interface TranslatedMenuContents {
  menuName?: string | null;
  menuDescription?: string | null;
  categories: TranslatedCategory[];
}

interface TranslatedCategory {
  originalIndex: number;
  name?: string | null;
  description?: string | null;
  items: TranslatedMenuItem[];
}

interface TranslatedMenuItem {
  originalIndex: number;
  name?: string | null;
  description?: string | null;
}

export interface MenuTranslationSummary {
  externalId: string;
  languageCode: string;
  languageName: string;
  status: TranslationStatus;
  isStale: boolean;
  lastUpdatedDate: string;
}

export function isActiveMenu(menu: TenantMenusDto | GeneratedTenantMenusDto): menu is TenantMenusDto {
  return 'isActive' in menu && typeof menu.isActive === 'boolean';
}

export function sortCategoriesByDisplayOrder<T extends { displayOrder?: number }>(categories: T[] | undefined): T[] {
  if (!categories) return [];
  const DEFAULT_ORDER = 0;
  return [...categories].sort((a, b) => (a.displayOrder ?? DEFAULT_ORDER) - (b.displayOrder ?? DEFAULT_ORDER));
}

export function sortMenuItemsByDisplayOrder<T extends { displayOrder?: number }>(items: T[] | undefined): T[] {
  if (!items) return [];
  const DEFAULT_ORDER = 0;
  return [...items].sort((a, b) => (a.displayOrder ?? DEFAULT_ORDER) - (b.displayOrder ?? DEFAULT_ORDER));
}

export function updateCategoryDisplayOrder(categories: Category[]): Category[] {
  return categories.map((category, index) => ({
    ...category,
    displayOrder: index,
  }));
}

export function updateMenuItemDisplayOrder(items: MenuItem[]): MenuItem[] {
  return items.map((item, index) => ({
    ...item,
    displayOrder: index,
  }));
}

export function generateUniqueId(prefix: string): string {
  idCounter += 1;
  return `${prefix}_${Date.now()}_${idCounter}`;
}

export function getFeaturedItems(contents: MenuContents | null | undefined): MenuItem[] {
  if (contents?.featuredSectionEnabled === false) return [];
  const allItems = (contents?.categories ?? []).flatMap((c) => c.items ?? []);
  const DEFAULT_ORDER = 0;
  return allItems
    .filter((item) => item.isFeatured === true && item.isAvailable !== false)
    .sort((a, b) => (a.featuredOrder ?? DEFAULT_ORDER) - (b.featuredOrder ?? DEFAULT_ORDER));
}

export function ensureMenuContentsHaveIds(contents: MenuContents | null | undefined): MenuContents {
  if (!contents) return { categories: [] };

  const categories = (contents.categories ?? []).map((category) => ({
    ...category,
    id: category.id ?? generateUniqueId('cat'),
    items: (category.items ?? []).map((item) => ({
      ...item,
      id: item.id ?? generateUniqueId('item'),
    })),
  }));

  return { ...contents, categories };
}
