/**
 * Custom hook for fetching a PUBLIC, ANONYMOUS survey draft by resume token.
 *
 * Calls the questioner API directly (no token/cookie). Returns the saved answers
 * used to prefill a resumed survey. Disabled when no token is supplied.
 */
import { useQuery } from '@tanstack/react-query';

import env from '../../config/environment';
import { get } from '../../lib/http/utils/methods';

import type { Question as ApiQuestionModel } from '../autoGeneratedHooks/questioner/models';
import type { UseQueryResult } from '@tanstack/react-query';

/** Respondent-saved draft answers. */
export interface PublicDraftDto {
  token?: string | null;
  questionerTemplateExternalId?: string | null;
  contents?: { questions?: ApiQuestionModel[] } | null;
}

async function fetchDraft(token: string, signal?: AbortSignal): Promise<PublicDraftDto> {
  return get<undefined, PublicDraftDto>(
    `/api/v1/public/drafts/${token}`,
    undefined,
    { withToken: false, withCredentials: false, baseURL: env.QUESTIONER_API_URL, signal },
  );
}

interface UseGetDraftResult {
  data: PublicDraftDto | undefined;
  isLoading: boolean;
  isError: boolean;
}

/** Hook for fetching a public survey draft by resume token (disabled when empty). */
export function useGetDraft(token: string): UseGetDraftResult {
  const enabled = token !== '';
  const query: UseQueryResult<PublicDraftDto> = useQuery({
    queryKey: ['public', 'draft', token],
    queryFn: async ({ signal }) => fetchDraft(token, signal),
    enabled,
    retry: false,
  });

  return { data: query.data, isLoading: enabled && query.isLoading, isError: query.isError };
}

export default useGetDraft;
