/**
 * Custom hook for submitting a PUBLIC, ANONYMOUS survey response.
 *
 * Posts directly to the questioner API (NOT via the BFF) so no cookie/token is
 * attached, mirroring {@link usePublicMenuGetById}'s direct-to-api pattern.
 *
 * It exposes the SAME mutation interface that `useQuizForm` consumes from
 * `useQuestionerWebCompletedQuestionersCreate()` — namely a `mutateAsync` that
 * accepts `{ data: CreateCompletedQuestionerRequest }` — so it drops in without
 * any change to the fill stack. The `questionerTemplateExternalId` field is
 * dropped from the request body (it lives in the route).
 */
import { useMutation } from '@tanstack/react-query';

import env from '../../config/environment';
import { post } from '../../lib/http/utils/methods';
import { isValueDefined } from '../../utils/is';

import type {
  CreateCompletedQuestionerRequest,
  QuestionerContents,
} from '../autoGeneratedHooks/questioner/models';

/** Server response: the created response's external ID. */
export interface PublicSubmitResponseResult {
  externalId?: string;
}

/** Optional respondent identity collected per the template's contact mode. */
export interface RespondentContact {
  name?: string;
  email?: string;
}

/** Public response body — the answers, minus `questionerTemplateExternalId`. */
export interface PublicResponseBody {
  name?: string;
  description?: string | null;
  contents?: QuestionerContents;
  respondentEmail?: string;
}

/**
 * Pure mapper: strips `questionerTemplateExternalId` from the payload that
 * `buildSubmissionPayload` produces, leaving the public response body shape.
 * When a respondent contact is supplied (Optional/Required modes) it overrides
 * the response name and carries the respondent email.
 */
export function toPublicResponseBody(
  data: CreateCompletedQuestionerRequest,
  respondent?: RespondentContact,
): PublicResponseBody {
  const trimmedName = respondent?.name?.trim();
  const trimmedEmail = respondent?.email?.trim();
  return {
    name: isValueDefined(trimmedName) && trimmedName !== '' ? trimmedName : data.name,
    description: data.description,
    contents: data.contents,
    respondentEmail: isValueDefined(trimmedEmail) && trimmedEmail !== '' ? trimmedEmail : undefined,
  };
}

/** Posts a public survey response without authentication. */
async function submitPublicResponse(
  externalId: string,
  data: CreateCompletedQuestionerRequest,
  respondent?: RespondentContact,
): Promise<PublicSubmitResponseResult> {
  return post<PublicResponseBody, PublicSubmitResponseResult>(
    `/api/v1/public/questionerTemplates/${externalId}/responses`,
    toPublicResponseBody(data, respondent),
    {
      withToken: false,
      withCredentials: false,
      baseURL: env.QUESTIONER_API_URL,
    },
  );
}

export interface UsePublicSubmitResponseResult {
  mutateAsync: (variables: { data: CreateCompletedQuestionerRequest }) => Promise<unknown>;
}

/**
 * Hook for submitting a public survey response.
 * Mirrors the `useQuestionerWebCompletedQuestionersCreate()` mutation interface
 * (a `mutateAsync` taking `{ data }`) so it can be passed straight to
 * `useQuizForm`. `getRespondent` is read at submit time so the latest contact
 * inputs (name/email) are included for Optional/Required templates.
 */
export function usePublicSubmitResponse(
  externalId: string,
  getRespondent?: () => RespondentContact | undefined,
): UsePublicSubmitResponseResult {
  const mutation = useMutation({
    mutationKey: ['publicSubmitResponse', externalId],
    mutationFn: async (variables: { data: CreateCompletedQuestionerRequest }) =>
      submitPublicResponse(externalId, variables.data, getRespondent?.()),
  });

  return { mutateAsync: mutation.mutateAsync };
}

export default usePublicSubmitResponse;
