import { useMutation } from '@tanstack/react-query';

import env from '../../config/environment';
import { post } from '../../lib/http/utils/methods';
import { isValueDefined } from '../../utils/is';

import type {
  CreateCompletedQuestionerRequest,
  QuestionerContents,
} from '../autoGeneratedHooks/questioner/models';

/** Server response: the created response's external ID. */
export interface PublicSubmitResponseResult {
  externalId?: string;
}

/** Optional respondent identity collected per the template's contact mode. */
export interface RespondentContact {
  name?: string;
  email?: string;
}

/** Public response body — the answers, minus `questionerTemplateExternalId`. */
export interface PublicResponseBody {
  name?: string;
  description?: string | null;
  contents?: QuestionerContents;
  respondentEmail?: string;
}

export function toPublicResponseBody(
  data: CreateCompletedQuestionerRequest,
  respondent?: RespondentContact,
): PublicResponseBody {
  const trimmedName = respondent?.name?.trim();
  const trimmedEmail = respondent?.email?.trim();
  return {
    name: isValueDefined(trimmedName) && trimmedName !== '' ? trimmedName : data.name,
    description: data.description,
    contents: data.contents,
    respondentEmail: isValueDefined(trimmedEmail) && trimmedEmail !== '' ? trimmedEmail : undefined,
  };
}

async function submitPublicResponse(
  externalId: string,
  data: CreateCompletedQuestionerRequest,
  respondent?: RespondentContact,
): Promise<PublicSubmitResponseResult> {
  return post<PublicResponseBody, PublicSubmitResponseResult>(
    `/api/v1/public/questionerTemplates/${externalId}/responses`,
    toPublicResponseBody(data, respondent),
    {
      withToken: false,
      withCredentials: false,
      baseURL: env.QUESTIONER_API_URL,
    },
  );
}

export interface UsePublicSubmitResponseResult {
  mutateAsync: (variables: { data: CreateCompletedQuestionerRequest }) => Promise<unknown>;
}

export function usePublicSubmitResponse(
  externalId: string,
  getRespondent?: () => RespondentContact | undefined,
): UsePublicSubmitResponseResult {
  const mutation = useMutation({
    mutationKey: ['publicSubmitResponse', externalId],
    mutationFn: async (variables: { data: CreateCompletedQuestionerRequest }) =>
      submitPublicResponse(externalId, variables.data, getRespondent?.()),
  });

  return { mutateAsync: mutation.mutateAsync };
}

export default usePublicSubmitResponse;
