import { useQuery } from '@tanstack/react-query';

import env from '../../config/environment';
import { get } from '../../lib/http/utils/methods';

import type { Question as ApiQuestionModel } from '../autoGeneratedHooks/questioner/models';
import type { UseQueryResult } from '@tanstack/react-query';

const MINUTES_5 = 5;
const SECONDS_PER_MINUTE = 60;
const MS_PER_SECOND = 1000;

const PUBLIC_SURVEY_STALE_TIME_MS = MINUTES_5 * SECONDS_PER_MINUTE * MS_PER_SECOND;

export interface PublicQuestionerTemplateDto {
  externalId?: string | null;
  name?: string | null;
  description?: string | null;
  contents?: { questions?: ApiQuestionModel[] } | null;
  acceptingResponses?: boolean | null;
  /** Respondent identity collection mode: 0=Anonymous, 1=Optional, 2=Required. */
  respondentContactMode?: number | null;
}

/** Query key for the public survey query. */
export const getPublicQuestionerTemplateQueryKey = (externalId: string): string[] => [
  'public',
  'survey',
  externalId,
];

async function fetchPublicQuestionerTemplate(
  externalId: string,
  signal?: AbortSignal,
): Promise<PublicQuestionerTemplateDto> {
  return get<undefined, PublicQuestionerTemplateDto>(
    `/api/v1/public/questionerTemplates/${externalId}`,
    undefined,
    {
      withToken: false,
      withCredentials: false,
      baseURL: env.QUESTIONER_API_URL,
      signal,
    },
  );
}

interface UsePublicQuestionerTemplateResult {
  data: PublicQuestionerTemplateDto | undefined;
  isLoading: boolean;
  isError: boolean;
  error: unknown;
  refetch: () => Promise<unknown>;
}

export function usePublicQuestionerTemplate(externalId: string): UsePublicQuestionerTemplateResult {
  const isValidId = externalId !== '';

  const query: UseQueryResult<PublicQuestionerTemplateDto> = useQuery({
    queryKey: getPublicQuestionerTemplateQueryKey(externalId),
    queryFn: async ({ signal }) => fetchPublicQuestionerTemplate(externalId, signal),
    enabled: isValidId,
    retry: false,
    staleTime: PUBLIC_SURVEY_STALE_TIME_MS,
  });

  return {
    data: query.data,
    isLoading: query.isLoading,
    isError: query.isError,
    error: query.error,
    refetch: query.refetch,
  };
}

export default usePublicQuestionerTemplate;
