/**
 * Custom hook for fetching a PUBLIC, ANONYMOUS survey (questioner template).
 *
 * This hook does NOT require authentication and is used for the public
 * respondent route (`/public/survey/{externalId}`). It calls the questioner
 * API directly (NOT via the BFF) so no cookie/token is attached, mirroring
 * {@link usePublicMenuGetById}.
 *
 * The returned `contents.questions` match the shape the existing fill UI
 * (`useQuizForm`) already renders, except each question's correct answer is
 * stripped server-side (respondent-safe).
 */
import { useQuery } from '@tanstack/react-query';

import env from '../../config/environment';
import { get } from '../../lib/http/utils/methods';

import type { Question as ApiQuestionModel } from '../autoGeneratedHooks/questioner/models';
import type { UseQueryResult } from '@tanstack/react-query';

/** Time constants for stale time calculation. */
const MINUTES_5 = 5;
const SECONDS_PER_MINUTE = 60;
const MS_PER_SECOND = 1000;

/** Stale time for public survey data (5 minutes). */
const PUBLIC_SURVEY_STALE_TIME_MS = MINUTES_5 * SECONDS_PER_MINUTE * MS_PER_SECOND;

/**
 * Respondent-safe public survey shape. Matches the `TemplateData` shape
 * `useQuizForm` consumes from the authenticated active-template hook.
 */
export interface PublicQuestionerTemplateDto {
  externalId?: string | null;
  name?: string | null;
  description?: string | null;
  contents?: { questions?: ApiQuestionModel[] } | null;
}

/** Query key for the public survey query. */
export const getPublicQuestionerTemplateQueryKey = (externalId: string): string[] => [
  'public',
  'survey',
  externalId,
];

/** Fetches a public survey by external ID without authentication. */
async function fetchPublicQuestionerTemplate(
  externalId: string,
  signal?: AbortSignal,
): Promise<PublicQuestionerTemplateDto> {
  return get<undefined, PublicQuestionerTemplateDto>(
    `/api/v1/public/questionerTemplates/${externalId}`,
    undefined,
    {
      withToken: false,
      withCredentials: false,
      baseURL: env.QUESTIONER_API_URL,
      signal,
    },
  );
}

interface UsePublicQuestionerTemplateResult {
  data: PublicQuestionerTemplateDto | undefined;
  isLoading: boolean;
  isError: boolean;
  error: unknown;
  refetch: () => Promise<unknown>;
}

/**
 * Hook for fetching a public survey by external ID.
 * Returns the subset of React Query state that the public fill screen needs,
 * shaped to match what `useQuizForm` expects from the active-template hook.
 */
export function usePublicQuestionerTemplate(externalId: string): UsePublicQuestionerTemplateResult {
  const isValidId = externalId !== '';

  const query: UseQueryResult<PublicQuestionerTemplateDto> = useQuery({
    queryKey: getPublicQuestionerTemplateQueryKey(externalId),
    queryFn: async ({ signal }) => fetchPublicQuestionerTemplate(externalId, signal),
    enabled: isValidId,
    retry: false,
    staleTime: PUBLIC_SURVEY_STALE_TIME_MS,
  });

  return {
    data: query.data,
    isLoading: query.isLoading,
    isError: query.isError,
    error: query.error,
    refetch: query.refetch,
  };
}

export default usePublicQuestionerTemplate;
