import { toPublicResponseBody } from './usePublicSubmitResponse';

import type { CreateCompletedQuestionerRequest } from '../autoGeneratedHooks/questioner/models';

describe('toPublicResponseBody', () => {
  it('drops questionerTemplateExternalId and keeps name/description/contents', () => {
    const input: CreateCompletedQuestionerRequest = {
      name: 'My Survey',
      description: 'A description',
      questionerTemplateExternalId: 'tpl-123',
      contents: { questions: [{ id: 'q1', name: 'Q1' }] },
    };

    const result = toPublicResponseBody(input);

    expect(result).toEqual({
      name: 'My Survey',
      description: 'A description',
      contents: { questions: [{ id: 'q1', name: 'Q1' }] },
    });
    expect('questionerTemplateExternalId' in result).toBe(false);
  });

  it('preserves a null description', () => {
    const input: CreateCompletedQuestionerRequest = {
      name: 'No Desc',
      description: null,
      questionerTemplateExternalId: 'tpl-1',
      contents: { questions: [] },
    };

    const result = toPublicResponseBody(input);

    expect(result.description).toBeNull();
    expect(result.name).toBe('No Desc');
  });

  it('passes through undefined fields without inventing values', () => {
    const input: CreateCompletedQuestionerRequest = {
      questionerTemplateExternalId: 'tpl-1',
    };

    const result = toPublicResponseBody(input);

    expect(result.name).toBeUndefined();
    expect(result.description).toBeUndefined();
    expect(result.contents).toBeUndefined();
  });
});
