/**
 * Custom hook for uploading a PUBLIC, ANONYMOUS file-upload answer.
 *
 * Posts multipart/form-data directly to the questioner API (NOT via the BFF) so
 * no cookie/token is attached, mirroring {@link usePublicSubmitResponse}'s
 * direct-to-api pattern (same base URL / anonymous posture). The multipart field
 * name is `File` (single file per request), per the backend contract.
 *
 * `errorMessageMode: 'none'` suppresses the global error modal so the renderer
 * can map the 400/404/409 error codes to inline, localized messages itself.
 */
import { useCallback } from 'react';

import env from '../../config/environment';
import { deffHttp } from '../../lib/axios';

import type { FileReference } from '../autoGeneratedHooks/questioner/models';
import type { AxiosRequestConfig } from 'axios';

const MULTIPART_FIELD_NAME = 'File';

export interface UploadFileParams {
  questionId: string;
  file: Blob;
  fileName: string;
  onProgress?: (fraction: number) => void;
  signal?: AbortSignal;
}

function buildUploadUrl(externalId: string, questionId: string): string {
  return `/api/v1/public/questionerTemplates/${externalId}/questions/${questionId}/files`;
}

async function uploadPublicFile(externalId: string, params: UploadFileParams): Promise<FileReference> {
  const formData = new FormData();
  formData.append(MULTIPART_FIELD_NAME, params.file, params.fileName);

  const config: AxiosRequestConfig = {
    url: buildUploadUrl(externalId, params.questionId),
    data: formData,
    baseURL: env.QUESTIONER_API_URL,
    withCredentials: false,
    headers: { 'Content-Type': 'multipart/form-data' },
    signal: params.signal,
    onUploadProgress: (event) => {
      const total = event.total;
      if (typeof total === 'number' && total > 0) params.onProgress?.(event.loaded / total);
    },
  };

  return deffHttp.post<FileReference>(config, {
    withToken: false,
    withCredentials: false,
    errorMessageMode: 'none',
  });
}

export interface UsePublicFileUploadResult {
  uploadFile: (params: UploadFileParams) => Promise<FileReference>;
}

/** Hook returning a bound `uploadFile` for the given survey external id. */
export function usePublicFileUpload(externalId: string): UsePublicFileUploadResult {
  const uploadFile = useCallback(
    async (params: UploadFileParams): Promise<FileReference> => uploadPublicFile(externalId, params),
    [externalId],
  );
  return { uploadFile };
}

export default usePublicFileUpload;
