import { useCallback, useMemo } from 'react';

import useCompletedQuestionersWithUsers from './useCompletedQuestionersWithUsers';
import { computeAnalytics } from '../../features/questioner/utils/analyticsAggregator';
import { useQuestionerWebQuestionerTemplatesGetActiveTemplate } from '../autoGeneratedHooks/questioner/questionertemplates/questionertemplates';

import type { AnalyticsStats } from '../../features/questioner/utils/analyticsAggregator';
import type { QuestionerTemplateDto } from '../autoGeneratedHooks/questioner/models/questionerTemplateDto';

/**
 * Composes completed-questioner responses with the active template and derives
 * client-side analytics for that template only.
 */
export function useQuizAnalytics(): {
  stats: AnalyticsStats;
  activeTemplate: QuestionerTemplateDto | null;
  isLoading: boolean;
  isError: boolean;
  refetch: () => void;
} {
  const responsesQuery = useCompletedQuestionersWithUsers();
  const activeTemplateQuery = useQuestionerWebQuestionerTemplatesGetActiveTemplate();

  const activeTemplate = activeTemplateQuery.data ?? null;
  const responses = responsesQuery.data;

  const stats = useMemo(
    () => computeAnalytics(activeTemplate, responses),
    [activeTemplate, responses],
  );

  const refetch = useCallback(() => {
    responsesQuery.refetch();
    activeTemplateQuery.refetch().catch(() => {});
  }, [responsesQuery, activeTemplateQuery]);

  return {
    stats,
    activeTemplate,
    isLoading: responsesQuery.isLoading || activeTemplateQuery.isLoading,
    isError: responsesQuery.isError || activeTemplateQuery.isError,
    refetch,
  };
}

export default useQuizAnalytics;
