import { useCallback, useMemo } from 'react';

import useCompletedQuestionersWithUsers from './useCompletedQuestionersWithUsers';
import { computeAnalytics } from '../../features/questioner/utils/analyticsAggregator';
import { computeFunnel } from '../../features/questioner/utils/analyticsFunnel';
import { getQuestions } from '../../features/questioner/utils/analyticsTally';
import { isNotEmptyString, isValueDefined } from '../../utils/is';
import { useQuestionerWebQuestionerTemplatesGetActiveTemplate } from '../autoGeneratedHooks/questioner/questionertemplates/questionertemplates';

import type { AnalyticsStats } from '../../features/questioner/utils/analyticsAggregator';
import type { FunnelStats } from '../../features/questioner/utils/analyticsTypes';
import type { CompletedQuestionerDto } from '../autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Question } from '../autoGeneratedHooks/questioner/models/question';
import type { QuestionerTemplateDto } from '../autoGeneratedHooks/questioner/models/questionerTemplateDto';

export interface QuizAnalyticsResult {
  stats: AnalyticsStats;
  /** Completion / answered-rate funnel — NOT abandonment drop-off (see analyticsFunnel). */
  funnel: FunnelStats;
  /** The active template's defined questions (for the crosstab pickers). */
  questions: Question[];
  /** Responses matching the active template (the crosstab join source). */
  matchingResponses: CompletedQuestionerDto[];
  activeTemplate: QuestionerTemplateDto | null;
  isLoading: boolean;
  isError: boolean;
  refetch: () => void;
}

function filterMatching(
  activeTemplate: QuestionerTemplateDto | null,
  responses: CompletedQuestionerDto[] | undefined,
): CompletedQuestionerDto[] {
  if (!isValueDefined(activeTemplate) || !isNotEmptyString(activeTemplate.externalId)) return [];
  const all = Array.isArray(responses) ? responses : [];
  return all.filter((r) => r.questionerTemplateExternalId === activeTemplate.externalId);
}

/**
 * Composes completed-questioner responses with the active template and derives
 * client-side analytics (distributions, completion/answered-rate funnel, and the inputs
 * for the interactive crosstab) for that template only.
 */
interface DerivedAnalytics {
  stats: AnalyticsStats;
  matchingResponses: CompletedQuestionerDto[];
  questions: Question[];
  funnel: FunnelStats;
}

/** Memoise the client-side aggregations derived from the active template + responses. */
function useDerivedAnalytics(
  activeTemplate: QuestionerTemplateDto | null,
  responses: CompletedQuestionerDto[] | undefined,
): DerivedAnalytics {
  const stats = useMemo(() => computeAnalytics(activeTemplate, responses), [activeTemplate, responses]);
  const matchingResponses = useMemo(() => filterMatching(activeTemplate, responses), [activeTemplate, responses]);
  const questions = useMemo(
    () => (isValueDefined(activeTemplate) ? getQuestions(activeTemplate) : []),
    [activeTemplate],
  );
  const funnel = useMemo(() => computeFunnel(questions, matchingResponses), [questions, matchingResponses]);
  return { stats, matchingResponses, questions, funnel };
}

export function useQuizAnalytics(): QuizAnalyticsResult {
  const responsesQuery = useCompletedQuestionersWithUsers();
  const activeTemplateQuery = useQuestionerWebQuestionerTemplatesGetActiveTemplate();

  const activeTemplate = activeTemplateQuery.data ?? null;
  const derived = useDerivedAnalytics(activeTemplate, responsesQuery.data);

  const refetch = useCallback(() => {
    responsesQuery.refetch();
    activeTemplateQuery.refetch().catch(() => {});
  }, [responsesQuery, activeTemplateQuery]);

  return {
    ...derived,
    activeTemplate,
    isLoading: responsesQuery.isLoading || activeTemplateQuery.isLoading,
    isError: responsesQuery.isError || activeTemplateQuery.isError,
    refetch,
  };
}

export default useQuizAnalytics;
