/**
 * Custom hook for saving a PUBLIC, ANONYMOUS survey draft ("save & resume").
 *
 * Posts directly to the questioner API (no token/cookie) and returns the resume
 * token. Mirrors the direct-to-api pattern of {@link usePublicSubmitResponse}.
 */
import { useMutation } from '@tanstack/react-query';

import env from '../../config/environment';
import { post } from '../../lib/http/utils/methods';

import type { QuestionerContents } from '../autoGeneratedHooks/questioner/models';

/** Request body for a draft save. */
export interface SaveDraftBody {
  draftToken?: string;
  contents: QuestionerContents;
  respondentEmail?: string;
}

/** Server response: the resume token (draft ExternalId). */
export interface SaveDraftResult {
  token: string;
}

async function saveDraft(externalId: string, body: SaveDraftBody): Promise<SaveDraftResult> {
  return post<SaveDraftBody, SaveDraftResult>(
    `/api/v1/public/questionerTemplates/${externalId}/draft`,
    body,
    {
      withToken: false,
      withCredentials: false,
      baseURL: env.QUESTIONER_API_URL,
    },
  );
}

export interface UseSaveDraftResult {
  mutateAsync: (body: SaveDraftBody) => Promise<SaveDraftResult>;
  isPending: boolean;
}

/** Hook for saving a public survey draft and receiving its resume token. */
export function useSaveDraft(externalId: string): UseSaveDraftResult {
  const mutation = useMutation({
    mutationKey: ['saveDraft', externalId],
    mutationFn: async (body: SaveDraftBody) => saveDraft(externalId, body),
  });

  return { mutateAsync: mutation.mutateAsync, isPending: mutation.isPending };
}

export default useSaveDraft;
