


/**
 * useQuizFormState - State management for quiz form.
 */
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import type { ScrollView, Animated } from 'react-native';

import { useQuizNavigation } from './useQuizNavigation';
import { getEntryByUiType } from '../../../components/DynamicForm/questionTypes/registry';
import { isValueDefined } from '../../../utils/is';
import { shouldSkipForForm, pageHasVisibleQuestion, findPageInDirection, mapApiQuestionToUi } from '../utils/quizHelpers';

import type { DynamicQuiz, Answer, Question as UiQuestion } from '../../../components/DynamicForm';
import type { ValidationMessages } from '../../../components/DynamicForm/questionTypes/validation';
import type { Question as ApiQuestionModel } from '../../../server/autoGeneratedHooks/questioner/models';

const ANIMATION_OFF = false;

interface TemplateData { externalId?: string | null; name?: string | null; description?: string | null; contents?: { questions?: ApiQuestionModel[] } | null; }

interface QuizFormState {
  form: DynamicQuiz | null;
  errors: Record<string, string>;
  currentPage: number;
  totalPages: number;
  currentQuestions: UiQuestion[];
  scrollRef: React.RefObject<ScrollView | null>;
  pageOpacity: Animated.Value;
  setForm: React.Dispatch<React.SetStateAction<DynamicQuiz | null>>;
  setErrors: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  setCurrentPage: React.Dispatch<React.SetStateAction<number>>;
  shouldSkip: (q: UiQuestion) => boolean;
  updateAnswer: (id: string, v: Answer) => void;
  validatePage: (p: number) => boolean;
  validateAllPages: () => boolean;
  navigation: ReturnType<typeof useQuizNavigation>;
}

interface FormEffectsDeps {
  data: TemplateData | undefined;
  tRef: React.RefObject<(k: string, d?: string) => string>;
  form: DynamicQuiz | null;
  currentPage: number;
  setForm: React.Dispatch<React.SetStateAction<DynamicQuiz | null>>;
  setCurrentPage: React.Dispatch<React.SetStateAction<number>>;
  setErrors: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  navigateToPage: (target: number, current: number, opts?: { animate?: boolean }) => void;
}

export function useQuizFormState(data: TemplateData | undefined, t: (k: string, d?: string) => string): QuizFormState {
  const [form, setForm] = useState<DynamicQuiz | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [currentPage, setCurrentPage] = useState<number>(1);
  const nav = useQuizNavigation(setCurrentPage);
  const tRef = useRef(t);
  tRef.current = t;

  const effectsDeps = useMemo(() => ({ data, tRef, form, currentPage, setForm, setCurrentPage, setErrors, navigateToPage: nav.navigateToPage }), [data, form, currentPage, nav.navigateToPage]);
  useFormEffects(effectsDeps);

  const shouldSkip = useCallback((q: UiQuestion): boolean => (isValueDefined(form) ? shouldSkipForForm(form, q) : false), [form]);
  const updateAnswer = useCallback((qId: string, v: Answer): void => {
    if (!isValueDefined(form)) return;
    const { next, cleared } = applyAnswerUpdate(form, qId, v);
    setForm(next); setErrors(clearErrorsFor(qId, cleared));
  }, [form]);
  const validatePage = useCallback((p: number): boolean => {
    if (!isValueDefined(form)) return false;
    const errs = collectErrors(form.questions.filter((q) => q.page === p), shouldSkip, buildValidationMessages(tRef.current));
    setErrors(errs); return Object.keys(errs).length === 0;
  }, [form, shouldSkip]);
  const validateAllPages = useCallback((): boolean => {
    if (!isValueDefined(form)) return false;
    const errs = collectErrors(form.questions, shouldSkip, buildValidationMessages(tRef.current));
    setErrors(errs); return Object.keys(errs).length === 0;
  }, [form, shouldSkip]);
  const totalPages = useMemo(() => (isValueDefined(form) ? countVisiblePages(form) : 0), [form]);
  const currentQuestions = useMemo(() => (isValueDefined(form) ? form.questions.filter((q) => q.page === currentPage).sort((a, b) => a.order - b.order) : []), [form, currentPage]);

  return { form, errors, currentPage, totalPages, currentQuestions, scrollRef: nav.scrollRef, pageOpacity: nav.pageOpacity, setForm, setErrors, setCurrentPage, shouldSkip, updateAnswer, validatePage, validateAllPages, navigation: nav };
}

function initFormFromData(data: TemplateData, t: (k: string, d?: string) => string): DynamicQuiz {
  const questions = (data.contents?.questions ?? [])
    .map((q: ApiQuestionModel, i: number) => mapApiQuestionToUi(q, i))
    .sort((a: UiQuestion, b: UiQuestion) => a.order - b.order);
  return { id: data.externalId ?? 'active-template', name: data.name ?? t('quizActive.title', 'Active Quiz'), description: data.description ?? undefined, questions };
}

/** Applies answer update and clears skip-dependent answers. */
function applyAnswerUpdate(form: DynamicQuiz, qId: string, v: Answer): { next: DynamicQuiz; cleared: string[] } {
  const cleared: string[] = [];
  const updated = form.questions.map((q) => (q.id === qId ? { ...q, answer: v } : q));
  const base: DynamicQuiz = { ...form, questions: updated };
  const afterSkip = base.questions.map<UiQuestion>((q) => {
    if (!shouldSkipForForm(base, q)) return q;
    if (isValueDefined(q.answer) && !cleared.includes(q.id)) cleared.push(q.id);
    return { ...q, answer: undefined };
  });
  return { next: { ...base, questions: afterSkip }, cleared };
}

/** Builds localized validation message templates from the translation function. */
function buildValidationMessages(t: (k: string, d?: string) => string): ValidationMessages {
  return {
    required: t('common.validation.required'),
    minLength: t('common.validation.minLength'),
    maxLength: t('common.validation.maxLength'),
    pattern: t('common.validation.pattern'),
    min: t('common.validation.min'),
    max: t('common.validation.max'),
    minSelections: t('common.validation.minSelections'),
    maxSelections: t('common.validation.maxSelections'),
  };
}

/** Collects per-type validation errors (required + validationRules) for given questions. */
function collectErrors(questions: UiQuestion[], skipFn: (q: UiQuestion) => boolean, messages: ValidationMessages): Record<string, string> {
  const errs: Record<string, string> = {};
  questions.forEach((q) => {
    if (skipFn(q)) return;
    const entry = getEntryByUiType(q.type);
    const error = entry.validate?.(q.answer, q, messages);
    if (isValueDefined(error) && error !== '') errs[q.id] = error;
  });
  return errs;
}

/** Returns error-clearing updater for a question and any cleared-by-skip IDs. */
function clearErrorsFor(qId: string, cleared: string[]): (prev: Record<string, string>) => Record<string, string> {
  return (prev) => { const n = { ...prev }; delete n[qId]; for (const id of cleared) delete n[id]; return n; };
}

/** Counts visible pages. */
function countVisiblePages(form: DynamicQuiz): number {
  return [...new Set(form.questions.map((q) => q.page))].filter((p) => pageHasVisibleQuestion(form, p)).length;
}

/** Hook managing form initialization and empty-page skip navigation. */
function useFormEffects({ data, tRef, form, currentPage, setForm, setCurrentPage, setErrors, navigateToPage }: FormEffectsDeps): void {
  useEffect(() => {
    if (data) { setForm(initFormFromData(data, tRef.current)); setCurrentPage(1); setErrors({}); }
  }, [data, setForm, setCurrentPage, setErrors, tRef]);

  useEffect(() => {
    if (!isValueDefined(form) || pageHasVisibleQuestion(form, currentPage)) return;
    const tgt = findPageInDirection(form, currentPage, 1) ?? findPageInDirection(form, currentPage, -1);
    if (isValueDefined(tgt) && tgt !== currentPage) navigateToPage(tgt, currentPage, { animate: ANIMATION_OFF });
  }, [form, currentPage, navigateToPage]);
}
