import React, { useMemo, useState } from 'react';

import { StyleSheet, Text, View } from 'react-native';

import { FM } from '@/localization/helpers';
import type { CompletedQuestionerDto } from '@/server/autoGeneratedHooks/questioner/models/completedQuestionerDto';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import { TestIds } from '@/shared/testIds';
import { useTheme } from '@/theme/hooks/useTheme';
import { isNotEmptyString, isValueDefined } from '@/utils/is';

import CrosstabGrid from './CrosstabGrid';
import CrosstabPicker from './CrosstabPicker';
import { computeCrosstab } from '../../utils/analyticsCrosstab';
import { getQuestionId, getQuestionName } from '../../utils/analyticsTally';


import type { CrosstabQuestionOption } from '../../utils/analyticsTypes';

const TITLE_FONT_SIZE = 15;
const TITLE_MARGIN_BOTTOM = 6;
const SUBTITLE_FONT_SIZE = 13;
const SUBTITLE_MARGIN_BOTTOM = 10;
const HINT_FONT_SIZE = 13;
const HINT_MARGIN_TOP = 10;

const styles = StyleSheet.create({
  container: {
    marginBottom: TITLE_MARGIN_BOTTOM,
  },
  title: {
    fontSize: TITLE_FONT_SIZE,
    fontWeight: '600',
    marginBottom: TITLE_MARGIN_BOTTOM,
  },
  subtitle: {
    fontSize: SUBTITLE_FONT_SIZE,
    marginBottom: SUBTITLE_MARGIN_BOTTOM,
  },
  hint: {
    fontSize: HINT_FONT_SIZE,
    marginTop: HINT_MARGIN_TOP,
  },
});

function toOptions(questions: Question[]): CrosstabQuestionOption[] {
  return questions
    .map((q) => ({ questionId: getQuestionId(q), questionName: getQuestionName(q) }))
    .filter((o) => isNotEmptyString(o.questionId));
}

interface CrosstabTableProps {
  questions: Question[];
  responses: CompletedQuestionerDto[];
}

/**
 * Interactive crosstab: two question-pair pickers (rows + columns) over a count matrix
 * joined from the responses that answered both questions. Fully client-side.
 */
const CrosstabTable = ({ questions, responses }: CrosstabTableProps): React.ReactElement => {
  const { theme } = useTheme();
  const { colors } = theme;
  const options = useMemo(() => toOptions(questions), [questions]);
  const [rowId, setRowId] = useState('');
  const [colId, setColId] = useState('');

  const bothPicked = isNotEmptyString(rowId) && isNotEmptyString(colId);
  const samePicked = bothPicked && rowId === colId;

  const crosstab = useMemo(
    () => (bothPicked && !samePicked ? computeCrosstab(questions, responses, rowId, colId) : null),
    [bothPicked, samePicked, questions, responses, rowId, colId],
  );

  const hasMatrix = isValueDefined(crosstab) && crosstab.matchedResponses > 0;

  const renderBody = (): React.ReactElement => {
    if (!bothPicked)
      return <Text style={[styles.hint, { color: colors.textSecondary }]}>{FM('quizAnalytics.crosstab.pickPrompt')}</Text>;
    if (samePicked)
      return <Text style={[styles.hint, { color: colors.textSecondary }]}>{FM('quizAnalytics.crosstab.samePicked')}</Text>;
    if (!hasMatrix)
      return <Text style={[styles.hint, { color: colors.textSecondary }]}>{FM('quizAnalytics.crosstab.noData')}</Text>;
    return (
      <>
        <CrosstabGrid crosstab={crosstab} />
        <Text style={[styles.hint, { color: colors.textSecondary }]}>
          {FM('quizAnalytics.crosstab.matchedResponses', String(crosstab.matchedResponses))}
        </Text>
      </>
    );
  };

  return (
    <View style={styles.container} testID={TestIds.QUIZ_ANALYTICS_CROSSTAB}>
      <Text style={[styles.title, { color: colors.text }]}>{FM('quizAnalytics.crosstab.title')}</Text>
      <Text style={[styles.subtitle, { color: colors.textSecondary }]}>{FM('quizAnalytics.crosstab.subtitle')}</Text>
      <CrosstabPicker
        label={FM('quizAnalytics.crosstab.rowPicker')}
        optionLabel={(name) => FM('quizAnalytics.crosstab.selectRowOption', name)}
        options={options}
        optionTestId={TestIds.QUIZ_ANALYTICS_CROSSTAB_ROW_OPTION}
        pickerHint={FM('quizAnalytics.crosstab.rowPickerHint')}
        selectedId={rowId}
        testID={TestIds.QUIZ_ANALYTICS_CROSSTAB_ROW_PICKER}
        onSelect={setRowId}
      />
      <CrosstabPicker
        label={FM('quizAnalytics.crosstab.colPicker')}
        optionLabel={(name) => FM('quizAnalytics.crosstab.selectColOption', name)}
        options={options}
        optionTestId={TestIds.QUIZ_ANALYTICS_CROSSTAB_COL_OPTION}
        pickerHint={FM('quizAnalytics.crosstab.colPickerHint')}
        selectedId={colId}
        testID={TestIds.QUIZ_ANALYTICS_CROSSTAB_COL_PICKER}
        onSelect={setColId}
      />
      {renderBody()}
    </View>
  );
};

export default CrosstabTable;
